Repository gardener/gardener-extensions, pull requests merged in 2019-07, with the labels that each got.

#172 support flexvolume for etcd storage class on AliCloud
  controllers/provider-alicloud/charts/provider-alicloud/templates/storageclass.yaml
  controllers/provider-alicloud/charts/provider-alicloud/values.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
Labels: needs/ok-to-test

#174 change checksum
  controllers/provider-alicloud/charts/provider-alicloud/templates/deployment.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-aws/charts/provider-aws/templates/deployment.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-azure/charts/provider-azure/templates/deployment.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-gcp/charts/provider-gcp/templates/deployment.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-openstack/charts/provider-openstack/templates/deployment.yaml
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-packet/charts/provider-packet/templates/deployment.yaml
  controllers/provider-packet/example/controller-registration.yaml
Labels: needs/ok-to-test

#176 support flexvolume for etcd storage class on AliCloud
  controllers/extension-certificate-service/example/controller-registration.yaml
  controllers/os-coreos-alicloud/example/controller-registration.yaml
  controllers/os-coreos/example/controller-registration.yaml
  controllers/os-suse-jeos/example/controller-registration.yaml
  controllers/provider-alicloud/charts/provider-alicloud/templates/storageclass.yaml
  controllers/provider-alicloud/charts/provider-alicloud/values.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-packet/example/controller-registration.yaml
Labels: needs/ok-to-test

#177 change checksum
  controllers/provider-alicloud/charts/provider-alicloud/templates/deployment.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-aws/charts/provider-aws/templates/deployment.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-azure/charts/provider-azure/templates/deployment.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-gcp/charts/provider-gcp/templates/deployment.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-openstack/charts/provider-openstack/templates/deployment.yaml
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-packet/charts/provider-packet/templates/deployment.yaml
  controllers/provider-packet/example/controller-registration.yaml
Labels: needs/ok-to-test

#179 fix error of provisioner value
  controllers/provider-alicloud/charts/provider-alicloud/templates/storageclass.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
Labels: needs/ok-to-test

#171 Fix contains string with prefix bug
  controllers/provider-alicloud/pkg/webhook/controlplane/ensurer.go
  controllers/provider-packet/pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplane/utils.go
Labels: needs/ok-to-test

#181 fix error of provisioner value
  controllers/provider-alicloud/charts/provider-alicloud/templates/storageclass.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
Labels: needs/ok-to-test

#185 Qualify image names
  .ci/component_descriptor
Labels: needs/ok-to-test

#186 Adapt CCM pod requests based on VPA recommendations
  controllers/provider-aws/charts/internal/cloud-controller-manager/values.yaml
  controllers/provider-azure/charts/internal/cloud-controller-manager/values.yaml
  controllers/provider-gcp/charts/internal/cloud-controller-manager/values.yaml
Labels: needs/ok-to-test

#187 Adapt requests for etcd backup-restore sidecar based on VPA recommendations
  pkg/webhook/controlplane/etcd.go
Labels: needs/ok-to-test

#190 PR-Template: add developer target group
  .github/pull_request_template.md
Labels: needs/ok-to-test

#193 enable encrypted flag in storageclass for Alicloud
  controllers/provider-alicloud/charts/provider-alicloud/templates/storageclass.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
Labels: needs/ok-to-test

#194 enable encrypted flag in storageclass for Alicloud
  controllers/extension-certificate-service/example/controller-registration.yaml
  controllers/os-coreos-alicloud/example/controller-registration.yaml
  controllers/os-coreos/example/controller-registration.yaml
  controllers/os-suse-jeos/example/controller-registration.yaml
  controllers/provider-alicloud/charts/provider-alicloud/templates/storageclass.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-packet/example/controller-registration.yaml
Labels: needs/ok-to-test

#196 Fix dep ensure
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_network.go
Labels: reviewed/ok-to-test

#103 Extension Controller with Support for Ubuntu OS
  Makefile
  controllers/hyper/cmd/gardener-extension-hyper/app/app.go
  controllers/os-ubuntu/README.md
  controllers/os-ubuntu/charts/os-ubuntu/.helmignore
  controllers/os-ubuntu/charts/os-ubuntu/Chart.yaml
  controllers/os-ubuntu/charts/os-ubuntu/doc.go
  controllers/os-ubuntu/charts/os-ubuntu/templates/deployment.yaml
  controllers/os-ubuntu/charts/os-ubuntu/templates/rbac.yaml
  controllers/os-ubuntu/charts/os-ubuntu/templates/serviceaccount.yaml
  controllers/os-ubuntu/charts/os-ubuntu/values.yaml
  controllers/os-ubuntu/cmd/gardener-extension-os-ubuntu/app/app.go
  controllers/os-ubuntu/cmd/gardener-extension-os-ubuntu/main.go
  controllers/os-ubuntu/example/controller-registration-local.yaml
  controllers/os-ubuntu/example/controller-registration.yaml
  controllers/os-ubuntu/example/crd-operatingsystemconfig.yaml
  controllers/os-ubuntu/example/operatingsystemconfig.yaml
  controllers/os-ubuntu/pkg/generator/generator.go
  controllers/os-ubuntu/pkg/generator/templates/cloud-init.template
  controllers/os-ubuntu/pkg/test_generator/generator_suite_test.go
  controllers/os-ubuntu/pkg/test_generator/generator_test.go
  controllers/os-ubuntu/pkg/test_generator/testfiles/cloud-init
  extensions.yaml
Labels: needs/ok-to-test

#197 Added vpa resource to all the controllers.
  controllers/os-coreos-alicloud/charts/os-coreos-alicloud/templates/_helpers.tpl
  controllers/os-coreos-alicloud/charts/os-coreos-alicloud/templates/os-coreos-alicloud-vpa.yaml
  controllers/os-coreos-alicloud/example/controller-registration.yaml
  controllers/os-coreos/charts/os-coreos/templates/_helpers.tpl
  controllers/os-coreos/charts/os-coreos/templates/os-coreos-vpa.yaml
  controllers/os-coreos/example/controller-registration.yaml
  controllers/os-suse-jeos/charts/os-suse-jeos/templates/_helpers.tpl
  controllers/os-suse-jeos/charts/os-suse-jeos/templates/os-suse-jeos-vpa.yaml
  controllers/os-suse-jeos/example/controller-registration.yaml
  controllers/provider-alicloud/charts/provider-alicloud/templates/_helpers.tpl
  controllers/provider-alicloud/charts/provider-alicloud/templates/provider-alicloud-vpa.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-aws/charts/provider-aws/templates/_helpers.tpl
  controllers/provider-aws/charts/provider-aws/templates/provider-aws-vpa.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-azure/charts/provider-azure/templates/_helpers.tpl
  controllers/provider-azure/charts/provider-azure/templates/provider-azure-vpa.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-gcp/charts/provider-gcp/templates/_helpers.tpl
  controllers/provider-gcp/charts/provider-gcp/templates/provider-gcp-vpa.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-local/charts/provider-local/templates/_helpers.tpl
  controllers/provider-local/charts/provider-local/templates/provider-local-vpa.yaml
  controllers/provider-openstack/charts/provider-openstack/templates/_helpers.tpl
  controllers/provider-openstack/charts/provider-openstack/templates/provider-openstack-vpa.yaml
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-packet/charts/provider-packet/templates/_helpers.tpl
  controllers/provider-packet/charts/provider-packet/templates/provider-packet-vpa.yaml
  controllers/provider-packet/example/controller-registration.yaml
Labels: needs/ok-to-test

#198 remove runtimeVersion (>= 1.14.x) specification for alicloud
  controllers/provider-alicloud/charts/images.yaml
Labels: needs/ok-to-test

#191 Added delay before removing OpenStack cloud controller manager
  controllers/provider-openstack/pkg/controller/controlplane/add.go
  controllers/provider-openstack/pkg/controller/controlplane/wrapper.go
Labels: needs/ok-to-test

#192 Create Credentialless Cloud-Config for Azure Workers
  controllers/provider-azure/charts/internal/cloud-provider-config/templates/azure-credentials.tpl
  controllers/provider-azure/charts/internal/cloud-provider-config/templates/cloud-provider-config.tpl
  controllers/provider-azure/charts/internal/cloud-provider-config/templates/cloud-provider-config.yaml
  controllers/provider-azure/charts/internal/cloud-provider-config/templates/cloud-provider-worker-config.yaml
  controllers/provider-azure/pkg/azure/types.go
  controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-azure/pkg/webhook/controlplane/ensurer.go
  controllers/provider-azure/pkg/webhook/controlplane/ensurer_test.go
Labels: needs/ok-to-test

#210 Remove insecure TLS cipher suites
  controllers/provider-aws/charts/internal/utils-tls-cipher-suites/templates/_tls_cipher_suites.tpl
  controllers/provider-azure/charts/internal/utils-tls-cipher-suites/templates/_tls_cipher_suites.tpl
  controllers/provider-gcp/charts/internal/utils-tls-cipher-suites/templates/_tls_cipher_suites.tpl
  controllers/provider-openstack/charts/internal/utils-tls-cipher-suites/templates/_tls_cipher_suites.tpl
Labels: needs/ok-to-test

#213 Added loadbalancer classes types
  controllers/provider-openstack/pkg/apis/openstack/types_controlplane.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/types_controlplane.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/zz_generated.conversion.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-openstack/pkg/apis/openstack/zz_generated.deepcopy.go
Labels: needs/ok-to-test

#214 Revert "Remove insecure TLS cipher suites"
  controllers/provider-aws/charts/internal/utils-tls-cipher-suites/templates/_tls_cipher_suites.tpl
  controllers/provider-azure/charts/internal/utils-tls-cipher-suites/templates/_tls_cipher_suites.tpl
  controllers/provider-gcp/charts/internal/utils-tls-cipher-suites/templates/_tls_cipher_suites.tpl
  controllers/provider-openstack/charts/internal/utils-tls-cipher-suites/templates/_tls_cipher_suites.tpl
Labels: kind/bug, needs/ok-to-test, priority/blocker, size/xs, topology/seed, topology/shoot

#211 Scale down/up cluster-autoscaler instead of deleting it
  pkg/controller/worker/genericactuator/actuator_reconcile.go
Labels: needs/ok-to-test

#215 Deploy MCM during Worker deletion
  Gopkg.lock
  Gopkg.toml
  controllers/extension-certificate-service/cmd/main.go
  controllers/hyper/cmd/gardener-extension-hyper/main.go
  controllers/os-coreos-alicloud/cmd/gardener-extension-os-coreos-alicloud/main.go
  controllers/os-coreos/cmd/gardener-extension-os-coreos/main.go
  controllers/os-suse-jeos/cmd/gardener-extension-os-suse-jeos/main.go
  controllers/os-ubuntu/cmd/gardener-extension-os-ubuntu/main.go
  controllers/provider-alicloud/cmd/gardener-extension-provider-alicloud/main.go
  controllers/provider-aws/cmd/gardener-extension-provider-aws/main.go
  controllers/provider-azure/cmd/gardener-extension-provider-azure/main.go
  controllers/provider-gcp/cmd/gardener-extension-provider-gcp/main.go
  controllers/provider-openstack/cmd/gardener-extension-provider-openstack/main.go
  controllers/provider-packet/cmd/gardener-extension-provider-packet/main.go
  pkg/controller/worker/genericactuator/actuator_delete.go
  pkg/controller/worker/genericactuator/actuator_reconcile.go
  pkg/controller/worker/genericactuator/machine_controller_manager.go
  pkg/log/log.go
Labels: kind/enhancement, needs/ok-to-test, priority/normal, size/m, topology/seed

#216 Gardener extensions for Alicloud now supports k8s 1.15.
  controllers/extension-certificate-service/example/controller-registration.yaml
  controllers/os-coreos-alicloud/example/controller-registration.yaml
  controllers/os-coreos/example/controller-registration.yaml
  controllers/os-suse-jeos/example/controller-registration.yaml
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-packet/example/controller-registration.yaml
Labels: needs/ok-to-test

#221 Fix disk format issue on AliCloud
  controllers/extension-certificate-service/example/controller-registration.yaml
  controllers/os-coreos-alicloud/example/controller-registration.yaml
  controllers/os-coreos/example/controller-registration.yaml
  controllers/os-suse-jeos/example/controller-registration.yaml
  controllers/os-ubuntu/example/controller-registration.yaml
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-packet/example/controller-registration.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test

#224 Add reconcile predicates to backup resources
  controllers/provider-aws/cmd/gardener-extension-provider-aws/app/app.go
  controllers/provider-aws/pkg/controller/backupbucket/add.go
  controllers/provider-aws/pkg/controller/backupentry/add.go
  controllers/provider-azure/cmd/gardener-extension-provider-azure/app/app.go
  controllers/provider-azure/pkg/controller/backupbucket/add.go
  controllers/provider-azure/pkg/controller/backupentry/add.go
  controllers/provider-gcp/cmd/gardener-extension-provider-gcp/app/app.go
  controllers/provider-gcp/pkg/controller/backupbucket/add.go
  controllers/provider-gcp/pkg/controller/backupentry/add.go
  pkg/controller/backupbucket/controller.go
  pkg/controller/backupentry/controller.go
  pkg/controller/backupentry/reconciler.go
  pkg/controller/reconciler.go
Labels: needs/ok-to-test

#225 Enhance os-ubuntu chart
  controllers/os-ubuntu/charts/os-ubuntu/templates/_helpers.tpl
  controllers/os-ubuntu/charts/os-ubuntu/templates/deployment.yaml
  controllers/os-ubuntu/charts/os-ubuntu/templates/os-ubuntu-vpa.yaml
  controllers/os-ubuntu/charts/os-ubuntu/values.yaml
  controllers/os-ubuntu/example/controller-registration.yaml
Labels: needs/ok-to-test
