Repository gardener/gardener-extensions, pull requests merged in 2019-08, with the labels that each got.

#229 Updated charts to support for MCM version 0.20.0
  controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-alicloud/charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
  controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-aws/charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
  controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-azure/charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
  controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-gcp/charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
  controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-openstack/charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
  controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-packet/charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
Labels: needs/ok-to-test

#231 [ci:component:github.com/gardener/machine-controller-manager:0.19.0->0.20.0]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: needs/ok-to-test

#234 Make certificate service use ManagedResources
  controllers/extension-certificate-service/charts/extension-certificate-service/templates/rbac.yaml
  controllers/extension-certificate-service/cmd/app/options.go
  controllers/extension-certificate-service/example/30-cluster.yaml
  controllers/extension-certificate-service/example/controller-registration.yaml
  controllers/extension-certificate-service/pkg/controller/certservice/actuator.go
  controllers/extension-certificate-service/pkg/controller/lifecycle/actuator.go
  controllers/os-coreos-alicloud/cmd/gardener-extension-os-coreos-alicloud/app/app.go
  controllers/os-coreos/cmd/gardener-extension-os-coreos/app/app.go
  controllers/provider-alicloud/cmd/gardener-extension-provider-alicloud/app/app.go
  controllers/provider-aws/cmd/gardener-extension-provider-aws/app/app.go
  controllers/provider-azure/cmd/gardener-extension-provider-azure/app/app.go
  controllers/provider-gcp/cmd/gardener-extension-provider-gcp/app/app.go
  controllers/provider-openstack/cmd/gardener-extension-provider-openstack/app/app.go
  controllers/provider-packet/cmd/gardener-extension-provider-packet/app/app.go
  pkg/controller/operatingsystemconfig/oscommon/app/app.go
  pkg/util/shoot.go
  pkg/util/shoot_test.go
  pkg/util/util.go
Labels: needs/ok-to-test

#228 Configure correct MTU on AWS seed and shoot nodes
  .ci/component_descriptor
  controllers/provider-aws/charts/images.yaml
  controllers/provider-aws/charts/provider-aws/templates/_images.tpl
  controllers/provider-aws/charts/provider-aws/templates/daemonset-custom-mtu.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-aws/pkg/webhook/controlplane/ensurer.go
  controllers/provider-aws/pkg/webhook/controlplane/ensurer_test.go
  pkg/mock/gardener-extensions/webhook/controlplane/genericmutator/mocks.go
  pkg/webhook/controlplane/genericmutator/mutator.go
  pkg/webhook/controlplane/genericmutator/mutator_test.go
  pkg/webhook/controlplane/genericmutator/noopensurer.go
  pkg/webhook/controlplane/utils.go
Labels: needs/ok-to-test

#236 Set hostname on AWS VMs to be the FQDN
  controllers/provider-aws/pkg/webhook/controlplane/ensurer.go
  controllers/provider-aws/pkg/webhook/controlplane/ensurer_test.go
Labels: needs/ok-to-test

#222 Added LoadBalancer Classes support for OpenStack Cloud Provider
  .ci/component_descriptor
  Gopkg.lock
  controllers/provider-azure/pkg/internal/imagevector/imagevector.go
  controllers/provider-openstack/README.md
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-openstack/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml
  controllers/provider-openstack/charts/internal/cloud-provider-config/templates/cloud-provider-config-cloud-controller-manager.yaml
  controllers/provider-openstack/charts/internal/cloud-provider-config/templates/cloud-provider-config-global.tpl
  controllers/provider-openstack/charts/internal/cloud-provider-config/templates/cloud-provider-config-kube-controller-manager.yaml
  controllers/provider-openstack/charts/internal/cloud-provider-config/templates/cloud-provider-config-meta.tpl
  controllers/provider-openstack/charts/internal/cloud-provider-config/templates/cloud-provider-config.yaml
  controllers/provider-openstack/charts/internal/cloud-provider-config/values.yaml
  controllers/provider-openstack/pkg/controller/controlplane/add.go
  controllers/provider-openstack/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-openstack/pkg/controller/controlplane/valuesprovider_test.go
  controllers/provider-openstack/pkg/controller/controlplane/wrapper.go
  controllers/provider-openstack/pkg/imagevector/imagevector.go
  controllers/provider-openstack/pkg/openstack/types.go
  controllers/provider-openstack/pkg/utils/utils.go
  controllers/provider-openstack/pkg/webhook/controlplane/ensurer.go
  controllers/provider-openstack/pkg/webhook/controlplane/ensurer_test.go
Labels: needs/ok-to-test

#242 [ci:component:github.com/gardener/machine-controller-manager:0.19.0->0.20.1]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: reviewed/ok-to-test

#244 Fix cloud-init templates for OS controllers
  controllers/os-suse-jeos/pkg/generator/generator.go
  controllers/os-suse-jeos/pkg/generator/templates/cloud-init-suse-jeos.template
  controllers/os-ubuntu/pkg/generator/generator.go
  controllers/os-ubuntu/pkg/generator/templates/cloud-init-ubuntu.template
Labels: needs/ok-to-test

#247 update csi plugin docker image for AliCloud
  controllers/provider-alicloud/charts/images.yaml
Labels: needs/ok-to-test

#245 Pagination for AWS ELB list call
  controllers/provider-aws/pkg/aws/client/client.go
Labels: needs/ok-to-test, reviewed/ok-to-test

#252 Remove redundant security context flags for CSI plugin for AliCloud
  controllers/provider-alicloud/charts/internal/shoot-system-components/charts/csi-alicloud/templates/csi-diskplugin-ds.yaml
Labels: needs/ok-to-test

#250 Fix the backup entry actuator logic
  pkg/controller/backupentry/genericactuator/actuator.go
  pkg/controller/backupentry/genericactuator/actuator_test.go
Labels: needs/ok-to-test

#251 Update default machine images
  controllers/provider-aws/charts/provider-aws/values.yaml
  controllers/provider-aws/example/00-componentconfig.yaml
  controllers/provider-aws/example/30-worker.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-azure/charts/provider-azure/values.yaml
  controllers/provider-azure/example/00-componentconfig.yaml
  controllers/provider-azure/example/30-worker.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-gcp/charts/provider-gcp/values.yaml
  controllers/provider-gcp/example/00-componentconfig.yaml
  controllers/provider-gcp/example/30-worker.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-openstack/charts/provider-openstack/values.yaml
  controllers/provider-openstack/example/00-componentconfig.yaml
  controllers/provider-openstack/example/30-worker.yaml
  controllers/provider-openstack/example/controller-registration.yaml
Labels: needs/ok-to-test

#253 [ci:component:github.com/gardener/etcd-backup-restore:0.6.4->0.7.0]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: needs/ok-to-test

#256 Remove two insecure TLS cipher suites
  controllers/provider-aws/charts/internal/utils-tls-cipher-suites/templates/_tls_cipher_suites.tpl
  controllers/provider-azure/charts/internal/utils-tls-cipher-suites/templates/_tls_cipher_suites.tpl
  controllers/provider-gcp/charts/internal/utils-tls-cipher-suites/templates/_tls_cipher_suites.tpl
  controllers/provider-openstack/charts/internal/utils-tls-cipher-suites/templates/_tls_cipher_suites.tpl
Labels: needs/ok-to-test

#258 Webhooks don't mutate objects if deletion timestamp is set
  controllers/provider-aws/pkg/webhook/shoot/mutator.go
  controllers/provider-packet/pkg/webhook/shoot/mutator.go
  pkg/webhook/controlplane/genericmutator/mutator.go
  pkg/webhook/network/mutator.go
Labels: needs/ok-to-test

#259 Remove controlplane wrapper from OpenStack provider
  controllers/provider-openstack/pkg/controller/controlplane/add.go
  controllers/provider-openstack/pkg/controller/controlplane/wrapper.go
Labels: needs/ok-to-test

#260 Ensure wake-up of provider specific components when hibernated shoot is deleted
  pkg/controller/controlplane/genericactuator/actuator.go
  pkg/controller/controlplane/reconciler.go
  pkg/controller/shoot.go
Labels: needs/ok-to-test

#254 Use backupEntryName as prefix for backup
  controllers/provider-alicloud/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-alicloud/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-aws/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-aws/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-azure/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-azure/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-gcp/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-gcp/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-openstack/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-openstack/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-packet/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-packet/pkg/webhook/controlplanebackup/ensurer_test.go
  go.mod
  go.sum
  pkg/webhook/controlplane/etcd.go
  vendor/github.com/gardener/gardener/pkg/apis/garden/types.go
  vendor/github.com/gardener/gardener/pkg/apis/garden/v1beta1/types.go
  vendor/github.com/gardener/gardener/pkg/apis/garden/v1beta1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/garden/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/operation/common/utils.go
  vendor/modules.txt
Labels: needs/ok-to-test

#261 add entrypted option for AliCloud Flexvolume storageclass
  controllers/provider-alicloud/charts/provider-alicloud/templates/storageclass.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
Labels: needs/ok-to-test

#263 Add Network CRD to provider-azure/examples
  controllers/provider-azure/example/20-crd-network.yaml
  extensions.yaml
Labels: needs/ok-to-test

#264 Add VPA for machine-controller-manager
  controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/vpa.yaml
  controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/values.yaml
  controllers/provider-alicloud/charts/provider-alicloud/templates/rbac.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/vpa.yaml
  controllers/provider-aws/charts/internal/machine-controller-manager/seed/values.yaml
  controllers/provider-aws/charts/provider-aws/templates/rbac.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/vpa.yaml
  controllers/provider-azure/charts/internal/machine-controller-manager/seed/values.yaml
  controllers/provider-azure/charts/provider-azure/templates/rbac.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/vpa.yaml
  controllers/provider-gcp/charts/internal/machine-controller-manager/seed/values.yaml
  controllers/provider-gcp/charts/provider-gcp/templates/rbac.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/vpa.yaml
  controllers/provider-openstack/charts/internal/machine-controller-manager/seed/values.yaml
  controllers/provider-openstack/charts/provider-openstack/templates/rbac.yaml
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/vpa.yaml
  controllers/provider-packet/charts/internal/machine-controller-manager/seed/values.yaml
  controllers/provider-packet/charts/provider-packet/templates/rbac.yaml
  controllers/provider-packet/example/controller-registration.yaml
Labels: needs/ok-to-test

#265 Add aws-lb-readvertiser-vpa to AWS
  controllers/provider-aws/charts/internal/aws-lb-readvertiser/templates/aws-lb-readvertiser-vpa.yaml
  controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go
Labels: needs/ok-to-test

#270 Minor nits
  Dockerfile
  controllers/extension-certificate-service/README.md
  controllers/extension-certificate-service/pkg/cmd/options.go
  controllers/extension-certificate-service/pkg/controller/lifecycle/internal/chartvalues_test.go
  controllers/networking-calico/README.md
  controllers/networking-calico/pkg/apis/calico/v1alpha1/types_network.go
  controllers/networking-calico/pkg/calico/types.go
  controllers/os-coreos-alicloud/README.md
  controllers/os-coreos/README.md
  controllers/os-suse-jeos/README.md
  controllers/os-ubuntu/README.md
  controllers/provider-alicloud/README.md
  controllers/provider-alicloud/pkg/webhook/controlplaneexposure/ensurer.go
  controllers/provider-aws/README.md
  controllers/provider-azure/README.md
  controllers/provider-azure/pkg/webhook/controlplaneexposure/ensurer.go
  controllers/provider-gcp/README.md
  controllers/provider-gcp/pkg/webhook/controlplaneexposure/ensurer.go
  controllers/provider-openstack/README.md
  controllers/provider-openstack/pkg/webhook/controlplaneexposure/ensurer.go
  controllers/provider-packet/README.md
  pkg/controller/worker/machine_crds.go
  pkg/inject/inject.go
  pkg/predicate/predicate_test.go
  pkg/webhook/registration.go
Labels: needs/ok-to-test, reviewed/ok-to-test

#269 Fix networking-calico controller flag
  controllers/networking-calico/charts/networking-calico/templates/deployment.yaml
  controllers/networking-calico/charts/networking-calico/values.yaml
  controllers/networking-calico/example/controller-registration.yaml
Labels: needs/ok-to-test

#271 Add export also for gnu-tar in hack/install-requirements.sh
  hack/install-requirements.sh
Labels: needs/ok-to-test

#267 Add logrotate and jq package. Disable cloud-init network configuration.
  controllers/os-ubuntu/pkg/generator/generator_suite_test.go
  controllers/os-ubuntu/pkg/generator/generator_test.go
  controllers/os-ubuntu/pkg/generator/templates/cloud-init-ubuntu.template
  controllers/os-ubuntu/pkg/generator/testfiles/cloud-init
Labels: needs/ok-to-test

#266 Fix AWS ControlPlane controller shoot delete flow
  controllers/provider-alicloud/pkg/alicloud/types.go
  controllers/provider-alicloud/pkg/controller/worker/machine_controller_manager.go
  controllers/provider-aws/pkg/aws/types.go
  controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-aws/pkg/controller/worker/machine_controller_manager.go
  controllers/provider-azure/pkg/azure/types.go
  controllers/provider-azure/pkg/controller/worker/machine_controller_manager.go
  controllers/provider-gcp/pkg/controller/worker/machine_controller_manager.go
  controllers/provider-gcp/pkg/gcp/types.go
  controllers/provider-openstack/pkg/controller/worker/machine_controller_manager.go
  controllers/provider-openstack/pkg/openstack/types.go
  controllers/provider-packet/pkg/controller/worker/machine_controller_manager.go
  controllers/provider-packet/pkg/packet/types.go
  go.mod
  go.sum
  pkg/controller/utils.go
  vendor/k8s.io/autoscaler/LICENSE
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/doc.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/register.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/types.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: needs/ok-to-test

#277 Fix MachineClass secrets cleanup for provider-aws
  controllers/provider-aws/pkg/controller/worker/machines.go
  controllers/provider-aws/pkg/controller/worker/machines_test.go
Labels: needs/ok-to-test

#278 ignore `NotFound` errors when deleting a `ControlPlane` resource
  pkg/controller/controlplane/genericactuator/actuator.go
Labels: needs/ok-to-test

#276 Fix networking-calico RBAC
  controllers/networking-calico/charts/internal/calico/templates/config.yaml
  controllers/networking-calico/charts/internal/calico/values.yaml
  controllers/networking-calico/charts/networking-calico/templates/rbac.yaml
  controllers/networking-calico/example/controller-registration.yaml
  controllers/networking-calico/pkg/charts/charts_test.go
  controllers/networking-calico/pkg/charts/utils.go
Labels: needs/ok-to-test

#279 add packr generate tag to image vector
  controllers/networking-calico/pkg/imagevector/imagevector.go
Labels: needs/ok-to-test

#273 add alicloud os ubuntu extension
  Makefile
  controllers/hyper/cmd/gardener-extension-hyper/app/app.go
  controllers/os-ubuntu-alicloud/charts/os-ubuntu-alicloud/.helmignore
  controllers/os-ubuntu-alicloud/charts/os-ubuntu-alicloud/Chart.yaml
  controllers/os-ubuntu-alicloud/charts/os-ubuntu-alicloud/doc.go
  controllers/os-ubuntu-alicloud/charts/os-ubuntu-alicloud/templates/_helpers.tpl
  controllers/os-ubuntu-alicloud/charts/os-ubuntu-alicloud/templates/deployment.yaml
  controllers/os-ubuntu-alicloud/charts/os-ubuntu-alicloud/templates/os-ubuntu-alicloud-vpa.yaml
  controllers/os-ubuntu-alicloud/charts/os-ubuntu-alicloud/templates/rbac.yaml
  controllers/os-ubuntu-alicloud/charts/os-ubuntu-alicloud/templates/serviceaccount.yaml
  controllers/os-ubuntu-alicloud/charts/os-ubuntu-alicloud/values.yaml
  controllers/os-ubuntu-alicloud/cmd/gardener-extension-os-ubuntu-alicloud/app/app.go
  controllers/os-ubuntu-alicloud/cmd/gardener-extension-os-ubuntu-alicloud/main.go
  controllers/os-ubuntu-alicloud/example/controller-registration-local.yaml
  controllers/os-ubuntu-alicloud/example/controller-registration.yaml
  controllers/os-ubuntu-alicloud/example/crd-operatingsystemconfig.yaml
  controllers/os-ubuntu-alicloud/example/operatingsystemconfig.yaml
  controllers/os-ubuntu-alicloud/pkg/generator/generator.go
  controllers/os-ubuntu-alicloud/pkg/generator/generator_suite_test.go
  controllers/os-ubuntu-alicloud/pkg/generator/generator_test.go
  controllers/os-ubuntu-alicloud/pkg/generator/templates/cloud-init.ubuntu-ali.template
  controllers/os-ubuntu-alicloud/pkg/generator/testfiles/cloud-init
  extensions.yaml
Labels: needs/ok-to-test

#284 [ci:component:github.com/gardener/machine-controller-manager:0.20.1->0.21.0]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: needs/ok-to-test

#285 Updated timeout and log levels for MCM
  controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
Labels: needs/ok-to-test

#288 [ci:component:github.com/gardener/machine-controller-manager:0.21.0->0.21.1]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: reviewed/ok-to-test

#289 [ci:component:github.com/gardener/etcd-backup-restore:0.7.0->0.7.1]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: reviewed/ok-to-test

#291 Fix ./.ci/prepare_release to generate the appropriate chart
  .ci/prepare_release
  controllers/extension-certificate-service/hack/generate-code.sh
  controllers/extension-certificate-service/pkg/apis/config/v1alpha1/zz_generated.defaults.go
  controllers/networking-calico/hack/generate-code
  controllers/networking-calico/pkg/apis/calico/v1alpha1/zz_generated.defaults.go
  controllers/provider-alicloud/hack/generate-code
  controllers/provider-alicloud/pkg/apis/alicloud/v1alpha1/zz_generated.defaults.go
  controllers/provider-alicloud/pkg/apis/config/v1alpha1/zz_generated.defaults.go
  controllers/provider-aws/hack/generate-code
  controllers/provider-aws/pkg/apis/aws/v1alpha1/zz_generated.defaults.go
  controllers/provider-aws/pkg/apis/config/v1alpha1/zz_generated.defaults.go
  controllers/provider-azure/hack/generate-code
  controllers/provider-azure/pkg/apis/azure/v1alpha1/zz_generated.defaults.go
  controllers/provider-azure/pkg/apis/config/v1alpha1/zz_generated.defaults.go
  controllers/provider-gcp/hack/generate-code
  controllers/provider-gcp/pkg/apis/config/v1alpha1/zz_generated.defaults.go
  controllers/provider-gcp/pkg/apis/gcp/v1alpha1/zz_generated.defaults.go
  controllers/provider-openstack/hack/generate-code
  controllers/provider-openstack/pkg/apis/config/v1alpha1/zz_generated.defaults.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/zz_generated.defaults.go
  controllers/provider-packet/hack/generate-code
  controllers/provider-packet/pkg/apis/config/v1alpha1/zz_generated.defaults.go
  controllers/provider-packet/pkg/apis/packet/v1alpha1/zz_generated.defaults.go
Labels: needs/ok-to-test

#295 Enable injecting images to networking-calico
  controllers/networking-calico/charts/networking-calico/templates/_helpers.tpl
  controllers/networking-calico/charts/networking-calico/templates/configmap-imagevector-overwrite.yaml
  controllers/networking-calico/charts/networking-calico/templates/deployment.yaml
  controllers/networking-calico/charts/networking-calico/values.yaml
  controllers/networking-calico/example/controller-registration.yaml
Labels: needs/ok-to-test

#286 Add extension controllers logging configuration
  controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-alicloud/charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/templates/alicloud-ccm-deployment.yaml
  controllers/provider-alicloud/charts/provider-alicloud/templates/configmap-logging.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-aws/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml
  controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-aws/charts/provider-aws/templates/configmap-logging.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-azure/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml
  controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-azure/charts/provider-azure/templates/configmap-logging.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-gcp/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml
  controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-gcp/charts/provider-gcp/templates/configmap-logging.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-openstack/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml
  controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-openstack/charts/provider-openstack/templates/configmap-logging.yaml
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-packet/charts/internal/seed-controlplane/charts/packet-cloud-controller-manager/templates/cloud-controller-manager.yaml
  controllers/provider-packet/charts/provider-packet/templates/configmap-logging.yaml
  controllers/provider-packet/example/controller-registration.yaml
Labels: needs/ok-to-test
