Repository gardener/gardener-extensions, pull requests merged in 2019-10, with the labels that each got.

#347 Allow extension charts to be used with SHA image tags
  controllers/networking-calico/charts/networking-calico/templates/deployment.yaml
  controllers/networking-calico/example/controller-registration.yaml
  controllers/os-ubuntu/charts/os-ubuntu/templates/deployment.yaml
  controllers/os-ubuntu/example/controller-registration.yaml
Labels: needs/ok-to-test

#348 Revert "Azure: Update deprecated terraform resources"
  controllers/provider-azure/charts/internal/azure-infra/templates/main.tf
Labels: kind/bug, needs/ok-to-test

#350 Add gardener extensions logo
  README.md
  logo/gardener-extension-180px.png
  logo/gardener-extensions.svg
Labels: needs/ok-to-test

#351 Added support for OpenStack CCM 1.16
  controllers/provider-openstack/charts/images.yaml
Labels: needs/ok-to-test

#352 Use shootUID for randomization of backup schedule
  controllers/provider-alicloud/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-aws/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-azure/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-gcp/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-openstack/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-packet/pkg/webhook/controlplanebackup/ensurer_test.go
  pkg/webhook/controlplane/etcd.go
Labels: needs/ok-to-test

#355 Fix cloud-init template to render properly OSC units
  controllers/os-coreos-alicloud/pkg/coreos-alicloud/internal/templates/cloud-init.sh.template
  controllers/os-coreos-alicloud/pkg/coreos-alicloud/internal/testfiles/cloud-init.sh
  controllers/os-ubuntu-alicloud/pkg/generator/templates/cloud-init.ubuntu-ali.template
  controllers/os-ubuntu-alicloud/pkg/generator/testfiles/cloud-init
Labels: needs/ok-to-test

#356 Vendor gardener/gardener@8493745aa2ee
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/pkg/utils/secrets/secrets.go
  vendor/modules.txt
Labels: needs/ok-to-test

#357 adding null checks for valueproviders
  controllers/provider-alicloud/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-gcp/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-openstack/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-packet/pkg/controller/controlplane/valuesprovider.go
Labels: needs/ok-to-test

#361 Fix: Azure lb issue in combination with avSet
  controllers/provider-azure/charts/internal/cloud-provider-config/templates/cloud-provider-config.tpl
  controllers/provider-azure/charts/internal/cloud-provider-config/values.yaml
  controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-azure/pkg/controller/controlplane/valuesprovider_test.go
Labels: kind/bug, needs/ok-to-test, platform/az

#363 Remove dead code
  controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go
Labels: needs/ok-to-test

#364 Enable golangci checks
  controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go
  hack/check.sh
Labels: needs/ok-to-test

#362 Raise resource requests/limits for cert-service
  controllers/extension-shoot-cert-service/charts/internal/shoot-cert-management-seed/values.yaml
Labels: needs/ok-to-test

#360 Switch on the bandwidth plugin for CNI config
  controllers/networking-calico/charts/internal/calico/templates/config.yaml
Labels: needs/ok-to-test

#366 [ci:component:github.com/gardener/terraformer:0.15.0->0.16.0]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: needs/ok-to-test

#365 Enable Using POD CIDRs on calico node/typha
  controllers/networking-calico/charts/internal/calico/templates/calico.yaml
Labels: needs/ok-to-test

#349 Add provider config generation for create shoot tests
  .test-defs/provider-alicloud.yaml
  .test-defs/provider-aws.yaml
  .test-defs/provider-azure.yaml
  .test-defs/provider-gcp.yaml
  .test-defs/provider-openstack.yaml
  controllers/provider-alicloud/test/tm/generator.go
  controllers/provider-aws/test/tm/generator.go
  controllers/provider-azure/test/tm/generator.go
  controllers/provider-gcp/test/tm/generator.go
  controllers/provider-openstack/test/tm/generator.go
  go.mod
  test/tm/generator/helper.go
Labels: needs/ok-to-test

#370 [ci:component:github.com/gardener/cert-management:0.2.2->0.2.3]
  controllers/extension-shoot-cert-service/charts/images.yaml
Labels: reviewed/ok-to-test

#377 [ci:component:github.com/gardener/external-dns-management:0.7.0->0.7.1]
  controllers/extension-shoot-dns-service/charts/images.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test

#378 Add missing owner reference to MCM cluster role
  controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml
  controllers/provider-alicloud/example/20-crd-managedresource.yaml
  controllers/provider-alicloud/example/20-crd-operatingsystemconfig.yaml
  controllers/provider-alicloud/example/20-crd-vpa.yaml
  controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml
  controllers/provider-aws/example/20-crd-managedresource.yaml
  controllers/provider-aws/example/20-crd-operatingsystemconfig.yaml
  controllers/provider-aws/example/20-crd-vpa.yaml
  controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml
  controllers/provider-azure/example/20-crd-managedresource.yaml
  controllers/provider-azure/example/20-crd-operatingsystemconfig.yaml
  controllers/provider-azure/example/20-crd-vpa.yaml
  controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml
  controllers/provider-gcp/example/20-crd-managedresource.yaml
  controllers/provider-gcp/example/20-crd-operatingsystemconfig.yaml
  controllers/provider-gcp/example/20-crd-vpa.yaml
  controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml
  controllers/provider-openstack/example/20-crd-managedresource.yaml
  controllers/provider-openstack/example/20-crd-operatingsystemconfig.yaml
  controllers/provider-openstack/example/20-crd-vpa.yaml
  controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml
  controllers/provider-packet/example/20-crd-managedresource.yaml
  controllers/provider-packet/example/20-crd-operatingsystemconfig.yaml
  controllers/provider-packet/example/20-crd-vpa.yaml
  go.sum
Labels: needs/ok-to-test

#376 Refactored Webhook Ensurer API
  controllers/provider-alicloud/pkg/webhook/controlplane/ensurer.go
  controllers/provider-alicloud/pkg/webhook/controlplane/ensurer_test.go
  controllers/provider-alicloud/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-alicloud/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-alicloud/pkg/webhook/controlplaneexposure/ensurer.go
  controllers/provider-alicloud/pkg/webhook/controlplaneexposure/ensurer_test.go
  controllers/provider-aws/pkg/webhook/controlplane/ensurer.go
  controllers/provider-aws/pkg/webhook/controlplane/ensurer_test.go
  controllers/provider-aws/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-aws/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-aws/pkg/webhook/controlplaneexposure/ensurer.go
  controllers/provider-aws/pkg/webhook/controlplaneexposure/ensurer_test.go
  controllers/provider-azure/pkg/webhook/controlplane/ensurer.go
  controllers/provider-azure/pkg/webhook/controlplane/ensurer_test.go
  controllers/provider-azure/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-azure/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-azure/pkg/webhook/controlplaneexposure/ensurer.go
  controllers/provider-azure/pkg/webhook/controlplaneexposure/ensurer_test.go
  controllers/provider-gcp/pkg/webhook/controlplane/ensurer.go
  controllers/provider-gcp/pkg/webhook/controlplane/ensurer_test.go
  controllers/provider-gcp/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-gcp/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-gcp/pkg/webhook/controlplaneexposure/ensurer.go
  controllers/provider-gcp/pkg/webhook/controlplaneexposure/ensurer_test.go
  controllers/provider-openstack/pkg/webhook/controlplane/ensurer.go
  controllers/provider-openstack/pkg/webhook/controlplane/ensurer_test.go
  controllers/provider-openstack/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-openstack/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-openstack/pkg/webhook/controlplaneexposure/ensurer.go
  controllers/provider-openstack/pkg/webhook/controlplaneexposure/ensurer_test.go
  controllers/provider-packet/pkg/webhook/controlplane/ensurer.go
  controllers/provider-packet/pkg/webhook/controlplane/ensurer_test.go
  controllers/provider-packet/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-packet/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-packet/pkg/webhook/controlplaneexposure/ensurer.go
  controllers/provider-packet/pkg/webhook/controlplaneexposure/ensurer_test.go
  pkg/mock/gardener-extensions/webhook/controlplane/genericmutator/mocks.go
  pkg/webhook/controlplane/genericmutator/mutator.go
  pkg/webhook/controlplane/genericmutator/mutator_test.go
  pkg/webhook/controlplane/genericmutator/noopensurer.go
Labels: needs/ok-to-test

#374 Add IPIP and IP Autodetection Method for calico controller
  controllers/networking-calico/charts/internal/calico/templates/calico.yaml
  controllers/networking-calico/charts/internal/calico/values.yaml
  controllers/networking-calico/example/10-crd-managedresource.yaml
  controllers/networking-calico/example/20-network.yaml
  controllers/networking-calico/hack/api-reference/calico.md
  controllers/networking-calico/pkg/apis/calico/types_network.go
  controllers/networking-calico/pkg/apis/calico/v1alpha1/types_network.go
  controllers/networking-calico/pkg/apis/calico/v1alpha1/zz_generated.conversion.go
  controllers/networking-calico/pkg/apis/calico/v1alpha1/zz_generated.deepcopy.go
  controllers/networking-calico/pkg/apis/calico/zz_generated.deepcopy.go
  controllers/networking-calico/pkg/charts/charts_test.go
  controllers/networking-calico/pkg/charts/utils.go
Labels: needs/ok-to-test

#382 [ci:component:github.com/gardener/machine-controller-manager:0.22.0->0.23.0]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: needs/ok-to-test

#383 Azure: Avoid parallel LoadBalancer operations
  controllers/provider-azure/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml
Labels: kind/bug, needs/ok-to-test, platform/az

#371 Azure: Allow to deploy cluster in existing vNets
  controllers/provider-azure/charts/internal/azure-infra/templates/main.tf
  controllers/provider-azure/charts/internal/azure-infra/values.yaml
  controllers/provider-azure/charts/internal/cloud-provider-config/templates/cloud-provider-config.tpl
  controllers/provider-azure/charts/internal/cloud-provider-config/values.yaml
  controllers/provider-azure/charts/internal/machineclass/templates/machineclass.yaml
  controllers/provider-azure/example/30-infrastructure.yaml
  controllers/provider-azure/hack/api-reference/api.md
  controllers/provider-azure/pkg/apis/azure/types_infrastructure.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/types_infrastructure.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/zz_generated.conversion.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-azure/pkg/apis/azure/validation/infrastructure.go
  controllers/provider-azure/pkg/apis/azure/validation/infrastructure_test.go
  controllers/provider-azure/pkg/apis/azure/zz_generated.deepcopy.go
  controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-azure/pkg/controller/worker/machines.go
  controllers/provider-azure/pkg/internal/infrastructure/terraform.go
  controllers/provider-azure/pkg/internal/infrastructure/terraform_test.go
Labels: needs/ok-to-test, platform/az

#386 add VPA for cloud-controller-managers
  controllers/provider-alicloud/charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/templates/_helpers.tpl
  controllers/provider-alicloud/charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/templates/vpa.yaml
  controllers/provider-aws/charts/internal/cloud-controller-manager/templates/_helpers.tpl
  controllers/provider-aws/charts/internal/cloud-controller-manager/templates/vpa.yaml
  controllers/provider-azure/charts/internal/cloud-controller-manager/templates/_helpers.tpl
  controllers/provider-azure/charts/internal/cloud-controller-manager/templates/vpa.yaml
  controllers/provider-gcp/charts/internal/cloud-controller-manager/templates/_helpers.tpl
  controllers/provider-gcp/charts/internal/cloud-controller-manager/templates/vpa.yaml
  controllers/provider-openstack/charts/internal/cloud-controller-manager/templates/_helpers.tpl
  controllers/provider-openstack/charts/internal/cloud-controller-manager/templates/vpa.yaml
  controllers/provider-packet/charts/internal/seed-controlplane/charts/packet-cloud-controller-manager/templates/_helpers.tpl
  controllers/provider-packet/charts/internal/seed-controlplane/charts/packet-cloud-controller-manager/templates/vpa.yaml
Labels: needs/ok-to-test

#375 Enable csi-sizer for alicloud and upgrade csi components
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-alicloud/charts/internal/seed-controlplane/charts/csi-alicloud/templates/csi-plugin-dep.yaml
  controllers/provider-alicloud/charts/internal/seed-controlplane/charts/csi-alicloud/values.yaml
  controllers/provider-alicloud/charts/internal/shoot-storageclasses/templates/storageclasses.yaml
  controllers/provider-alicloud/charts/internal/shoot-system-components/charts/csi-alicloud/templates/auth/csi-attacher-rbac.yaml
  controllers/provider-alicloud/charts/internal/shoot-system-components/charts/csi-alicloud/templates/auth/csi-plugin-psp.yaml
  controllers/provider-alicloud/charts/internal/shoot-system-components/charts/csi-alicloud/templates/auth/csi-plugin-rbac.yaml
  controllers/provider-alicloud/charts/internal/shoot-system-components/charts/csi-alicloud/templates/auth/csi-provisioner-rbac.yaml
  controllers/provider-alicloud/charts/internal/shoot-system-components/charts/csi-alicloud/templates/auth/csi-resizer-rbac.yaml
  controllers/provider-alicloud/charts/internal/shoot-system-components/charts/csi-alicloud/templates/auth/csi-snapshotter-rbac.yaml
  controllers/provider-alicloud/pkg/alicloud/types.go
  controllers/provider-alicloud/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-alicloud/pkg/controller/controlplane/valuesprovider_test.go
  controllers/provider-alicloud/pkg/webhook/controlplane/ensurer.go
  controllers/provider-alicloud/pkg/webhook/controlplane/ensurer_test.go
  pkg/controller/shoot.go
Labels: needs/ok-to-test

#381 Reduce limits for control plane components for which VPA is deployed
  controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
Labels: needs/ok-to-test

#389 Bump Gardener version to fix vendor issues
  go.mod
  go.sum
  vendor/modules.txt
Labels: needs/ok-to-test

#390 Vendor github.com/gardener/gardener@9928f1a9ddd4
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/pkg/operation/terraformer/config.go
  vendor/github.com/gardener/gardener/pkg/operation/terraformer/terraformer.go
  vendor/modules.txt
Labels: needs/ok-to-test

#394 Revert "include controller dirname in logical image name"
  .ci/component_descriptor
Labels: needs/ok-to-test

#395 [ci:component:github.com/gardener/cert-management:0.2.3->0.2.4]
  controllers/extension-shoot-cert-service/charts/images.yaml
Labels: needs/ok-to-test

#396 [ci:component:github.com/gardener/cert-management:0.2.4->0.2.5]
  controllers/extension-shoot-cert-service/charts/images.yaml
Labels: needs/ok-to-test

#398 Fix machineclass generation for cloudnat
  controllers/provider-gcp/charts/internal/machineclass/templates/machineclass.yaml
  controllers/provider-gcp/charts/internal/machineclass/values.yaml
  controllers/provider-gcp/pkg/controller/worker/machines.go
  controllers/provider-gcp/pkg/controller/worker/machines_test.go
Labels: needs/ok-to-test

#402 Fix invalid check in control plane values provider for AWS
  controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go
Labels: needs/ok-to-test
