Repository gardener/gardener-extensions, pull requests merged in 2019-03, with the labels that each got.

#29 Fix target name
  .ci/pipeline_definitions
Labels: needs/ok-to-test

#33 Black list SCTP protocol (CVE-2019-3874)
  controllers/os-coreos/pkg/coreos/actuator_reconcile.go
Labels: area/security, exp/expert, kind/enhancement, priority/normal, reviewed/lgtm, status/accepted, topology/shoot

#34 Black list SCTP protocol for alicloud (CVE-2019-3874)
  controllers/os-coreos-alicloud/pkg/coreos-alicloud/actuator_reconcile.go
Labels: area/security, exp/expert, kind/enhancement, priority/normal, reviewed/lgtm, size/xs, status/accepted, topology/shoot
