Repository gardener/gardener-extensions, pull requests merged in 2019-12, with the labels that each got.

#475 [ci:component:github.com/gardener/cert-management:0.2.8->v0.2.9]
  controllers/extension-shoot-cert-service/charts/images.yaml
Labels: needs/ok-to-test

#474 Change computation of hash value for machine resources
  controllers/provider-alicloud/pkg/controller/worker/machines.go
  controllers/provider-alicloud/pkg/controller/worker/machines_test.go
  controllers/provider-aws/pkg/controller/worker/machines.go
  controllers/provider-aws/pkg/controller/worker/machines_test.go
  controllers/provider-azure/pkg/controller/worker/machines.go
  controllers/provider-azure/pkg/controller/worker/machines_test.go
  controllers/provider-gcp/pkg/controller/worker/machines.go
  controllers/provider-gcp/pkg/controller/worker/machines_test.go
  controllers/provider-openstack/pkg/controller/worker/machines.go
  controllers/provider-openstack/pkg/controller/worker/machines_test.go
  controllers/provider-packet/pkg/controller/worker/machines.go
  controllers/provider-packet/pkg/controller/worker/machines_test.go
  go.sum
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: needs/ok-to-test

#477 Enhance extension-shoot-cert-service to be able to use image overwrite
  controllers/extension-shoot-cert-service/charts/extension-shoot-cert-service/templates/_helpers.tpl
  controllers/extension-shoot-cert-service/charts/extension-shoot-cert-service/templates/configmap-imagevector-overwrite.yaml
  controllers/extension-shoot-cert-service/charts/extension-shoot-cert-service/templates/deployment.yaml
  controllers/extension-shoot-cert-service/charts/extension-shoot-cert-service/values.yaml
  controllers/extension-shoot-cert-service/example/controller-registration.yaml
Labels: needs/ok-to-test

#478 Remove all rules from default AWS VPC security group
  controllers/provider-aws/charts/internal/aws-infra/templates/main.tf
Labels: needs/ok-to-test

#484 Enhance extension-shoot-cert-service to be able to use image overwrite
  controllers/extension-shoot-cert-service/charts/extension-shoot-cert-service/templates/_helpers.tpl
  controllers/extension-shoot-cert-service/charts/extension-shoot-cert-service/templates/configmap-imagevector-overwrite.yaml
  controllers/extension-shoot-cert-service/charts/extension-shoot-cert-service/templates/deployment.yaml
  controllers/extension-shoot-cert-service/charts/extension-shoot-cert-service/values.yaml
  controllers/extension-shoot-cert-service/example/controller-registration.yaml
Labels: needs/ok-to-test

#486 [ci:component:github.com/gardener/cert-management:v0.2.9->v0.2.10]
  controllers/extension-shoot-cert-service/charts/images.yaml
Labels: needs/ok-to-test

#481 Vendor sigs.k8s.io/controller-runtime@v0.2.2
  controllers/os-suse-jeos/pkg/generator/generator.go
  controllers/provider-alicloud/cmd/gardener-extension-provider-alicloud/app/app.go
  controllers/provider-alicloud/test/e2e/networkpolicies/networkpolicy_test.go
  controllers/provider-aws/cmd/gardener-extension-provider-aws/app/app.go
  controllers/provider-aws/cmd/gardener-extension-validator-aws/app/app.go
  controllers/provider-aws/cmd/gardener-extension-validator-aws/app/options.go
  controllers/provider-aws/test/e2e/networkpolicies/networkpolicy_test.go
  controllers/provider-azure/cmd/gardener-extension-provider-azure/app/app.go
  controllers/provider-azure/test/e2e/networkpolicies/networkpolicy_test.go
  controllers/provider-gcp/cmd/gardener-extension-provider-gcp/app/app.go
  controllers/provider-gcp/test/e2e/networkpolicies/networkpolicy_test.go
  controllers/provider-openstack/cmd/gardener-extension-provider-openstack/app/app.go
  controllers/provider-openstack/test/e2e/networkpolicies/networkpolicy_test.go
  controllers/provider-packet/cmd/gardener-extension-provider-packet/app/app.go
  go.mod
  go.sum
  pkg/controller/backupbucket/controller.go
  pkg/controller/backupentry/controller.go
  pkg/controller/cmd/options.go
  pkg/controller/controlplane/controller.go
  pkg/controller/controlplane/predicate.go
  pkg/controller/extension/reconciler.go
  pkg/controller/infrastructure/controller.go
  pkg/controller/network/controller.go
  pkg/controller/operatingsystemconfig/controller.go
  pkg/controller/worker/controller.go
  pkg/log/log.go
  pkg/predicate/predicate.go
  pkg/webhook/cmd/options.go
  pkg/webhook/controlplane/etcd.go
  test/e2e/framework/networkpolicies/generators/networkpolicies.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.pb.go
  vendor/github.com/googleapis/gnostic/compiler/reader.go
  vendor/github.com/googleapis/gnostic/extensions/COMPILE-EXTENSION.sh
  vendor/github.com/googleapis/gnostic/extensions/extension.pb.go
  vendor/gomodules.xyz/jsonpatch/v2/.gitignore
  vendor/gomodules.xyz/jsonpatch/v2/.travis.yml
  vendor/gomodules.xyz/jsonpatch/v2/CHANGELOG.md
  vendor/gomodules.xyz/jsonpatch/v2/README.md
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/.travis.yml
  vendor/sigs.k8s.io/controller-runtime/Gopkg.lock
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/eventhandler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/recorder/recorder.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/zap.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go
Labels: needs/ok-to-test

#483 make customized image optional and add error message
  controllers/provider-alicloud/charts/provider-alicloud/templates/secret.yaml
  controllers/provider-alicloud/charts/provider-alicloud/values.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-alicloud/pkg/cmd/config.go
  controllers/provider-alicloud/pkg/controller/infrastructure/actuator.go
  controllers/provider-alicloud/pkg/controller/infrastructure/add.go
Labels: needs/ok-to-test

#485 Add deletion logic of NLBs
  controllers/provider-aws/pkg/aws/client/client.go
  controllers/provider-aws/pkg/aws/client/types.go
  controllers/provider-aws/pkg/controller/infrastructure/actuator_delete.go
  vendor/github.com/aws/aws-sdk-go/service/elbv2/api.go
  vendor/github.com/aws/aws-sdk-go/service/elbv2/doc.go
  vendor/github.com/aws/aws-sdk-go/service/elbv2/elbv2iface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/elbv2/errors.go
  vendor/github.com/aws/aws-sdk-go/service/elbv2/service.go
  vendor/github.com/aws/aws-sdk-go/service/elbv2/waiters.go
  vendor/modules.txt
Labels: needs/ok-to-test

#487 [release-1.0] Upgrade shoot-cert-service image version to v0.2.10
  controllers/extension-shoot-cert-service/charts/images.yaml
Labels: needs/ok-to-test

#460 Calico bare metal
  controllers/networking-calico/charts/internal/calico/templates/calico.yaml
  controllers/networking-calico/charts/internal/calico/values.yaml
  controllers/networking-calico/hack/api-reference/calico.md
  controllers/networking-calico/pkg/apis/calico/types_network.go
  controllers/networking-calico/pkg/apis/calico/v1alpha1/types_network.go
  controllers/networking-calico/pkg/apis/calico/v1alpha1/zz_generated.conversion.go
  controllers/networking-calico/pkg/apis/calico/v1alpha1/zz_generated.deepcopy.go
  controllers/networking-calico/pkg/apis/calico/zz_generated.deepcopy.go
  controllers/networking-calico/pkg/charts/charts_test.go
  controllers/networking-calico/pkg/charts/utils.go
  controllers/networking-calico/pkg/charts/values.go
  controllers/provider-azure/pkg/webhook/network/mutate.go
Labels: needs/ok-to-test

#488 making vpa configurable via helm chart for all providers
  controllers/provider-alicloud/charts/provider-alicloud/templates/vpa.yaml
  controllers/provider-alicloud/charts/provider-alicloud/values.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-aws/charts/provider-aws/templates/vpa.yaml
  controllers/provider-aws/charts/provider-aws/values.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-azure/charts/provider-azure/templates/vpa.yaml
  controllers/provider-azure/charts/provider-azure/values.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-gcp/charts/provider-gcp/templates/vpa.yaml
  controllers/provider-gcp/charts/provider-gcp/values.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-openstack/charts/provider-openstack/templates/vpa.yaml
  controllers/provider-openstack/charts/provider-openstack/values.yaml
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-packet/charts/provider-packet/templates/vpa.yaml
  controllers/provider-packet/charts/provider-packet/values.yaml
  controllers/provider-packet/example/controller-registration.yaml
Labels: needs/ok-to-test

#489 use released versions for packethost
  controllers/provider-packet/charts/images.yaml
Labels: needs/ok-to-test

#490 Update to stable "rbac.authorization.k8s.io/v1"
  controllers/extension-shoot-cert-service/charts/extension-shoot-cert-service/templates/rbac-shoot-cert-service.yaml
  controllers/extension-shoot-cert-service/charts/internal/shoot-cert-management-seed/templates/rbac.yaml
  controllers/extension-shoot-cert-service/charts/internal/shoot-cert-management-shoot/templates/rbac.yaml
  controllers/extension-shoot-cert-service/example/25-rbac.yaml
  controllers/extension-shoot-cert-service/example/controller-registration.yaml
Labels: needs/ok-to-test

#491 [ci:component:github.com/gardener/machine-controller-manager:0.24.0->v0.25.0]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: needs/ok-to-test

#494 Update dns-controller-manager to v0.7.3
  controllers/extension-shoot-dns-service/charts/images.yaml
Labels: needs/ok-to-test

#465 Split calico chart files
  controllers/networking-calico/charts/internal/calico/templates/calico-typha.yaml
  controllers/networking-calico/charts/internal/calico/templates/calico.yaml
  controllers/networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-bgpconfigurations.yaml
  controllers/networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-bgppeers.yaml
  controllers/networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-blockaffinities.yaml
  controllers/networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-clusterinformations.yaml
  controllers/networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-felixconfigurations.yaml
  controllers/networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-globalnetworkpolicies.yaml
  controllers/networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-globalnetworksets.yaml
  controllers/networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-hostendpoints.yaml
  controllers/networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-ipamblocks.yaml
  controllers/networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-ipamconfigs.yaml
  controllers/networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-ipamhandles.yaml
  controllers/networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-ippools.yaml
  controllers/networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-networkpolicies.yaml
  controllers/networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-networksets.yaml
  controllers/networking-calico/charts/internal/calico/templates/kube-controller/clusterrole-calico-kube-controllers.yaml
  controllers/networking-calico/charts/internal/calico/templates/kube-controller/clusterrole-garden-psp-calico-kube-controllers.yaml
  controllers/networking-calico/charts/internal/calico/templates/kube-controller/clusterrolebinding-calico-kube-controllers.yaml
  controllers/networking-calico/charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
  controllers/networking-calico/charts/internal/calico/templates/kube-controller/psp-calico-kube-controllers.yaml
  controllers/networking-calico/charts/internal/calico/templates/kube-controller/rolebinding-garden-psp-calico-kube-controllers.yaml
  controllers/networking-calico/charts/internal/calico/templates/kube-controller/serviceaccount-calico-kube-controllers.yaml
  controllers/networking-calico/charts/internal/calico/templates/node/clusterrole-calico-node.yaml
  controllers/networking-calico/charts/internal/calico/templates/node/clusterrole-garden-psp-calico.yaml
  controllers/networking-calico/charts/internal/calico/templates/node/clusterrolebinding-calico-node.yaml
  controllers/networking-calico/charts/internal/calico/templates/node/configmap-calico-config.yaml
  controllers/networking-calico/charts/internal/calico/templates/node/daemonset-calico-node.yaml
  controllers/networking-calico/charts/internal/calico/templates/node/psp-calico.yaml
  controllers/networking-calico/charts/internal/calico/templates/node/rolebinding-garden-psp-calico.yaml
  controllers/networking-calico/charts/internal/calico/templates/node/serviceaccount-calico-node.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpha/clusterrole-gardener-psp-typha-cpha.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpha/clusterrole-typha-cpha.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpha/clusterrolebinding-typha-cpha.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpha/configmap-typha-horizontal-autoscaling.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpha/psp-gardener-typha-cpa.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpha/role-typha-cpha.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpha/rolebinding-gardener-psp-typha-cpa.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpha/rolebinding-typha-cpha.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpha/serviceaccount-typha-cpha.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpva/clusterrole-gardener-psp-typha-cpva.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpva/clusterrole-typha-cpva.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpva/clusterrolebinding-typha-cpva.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpva/configmap-typha-vertical-autoscaling.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpva/psp-gardener-typha-cpva.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpva/rolebinding-gardener-psp-typha-cpva.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpva/serviceaccount-typha-cpva.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha/clusterrole-garden-psp-calico-typha.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha/deployment-calico-typha.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha/pdb-calico-typha.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha/psp-gardener-calico-typha.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha/rolebinding-garden-psp-calico-typha.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha/service-calico-typha.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha/serviceaccount-calico-typha.yaml
  controllers/networking-calico/hack/api-reference/calico.md
  controllers/networking-calico/pkg/apis/calico/types_network.go
  controllers/networking-calico/pkg/apis/calico/v1alpha1/types_network.go
Labels: area/networking, kind/cleanup, needs/ok-to-test, topology/shoot

#500 Use MTU of 1460 for all SUSE nodes
  controllers/networking-calico/docs/usage-as-end-user.md
  controllers/os-suse-jeos/pkg/generator/templates/cloud-init/suse-jeos.template
  controllers/os-suse-jeos/pkg/generator/templates/script/suse-jeos.template
  controllers/os-suse-jeos/pkg/generator/testfiles/cloud-init/cloud-init
  controllers/os-suse-jeos/pkg/generator/testfiles/script/cloud-init
Labels: needs/ok-to-test

#476 Put Infrastructure state into status as runtime.RawExtension
  controllers/provider-alicloud/pkg/controller/infrastructure/actuator.go
  controllers/provider-alicloud/pkg/controller/infrastructure/actuator_test.go
  controllers/provider-aws/pkg/controller/infrastructure/actuator_reconcile.go
  controllers/provider-azure/pkg/controller/infrastructure/actuator.go
  controllers/provider-azure/pkg/controller/infrastructure/actuator_reconcile.go
  controllers/provider-gcp/pkg/controller/infrastructure/actuator.go
  controllers/provider-gcp/pkg/controller/infrastructure/actuator_reconcile.go
  controllers/provider-openstack/pkg/controller/infrastructure/actuator.go
  controllers/provider-openstack/pkg/controller/infrastructure/actuator_reconcile.go
  controllers/provider-packet/pkg/controller/infrastructure/actuator_reconcile.go
  pkg/mock/gardener-extensions/terraformer/mocks.go
  pkg/terraformer/config.go
  pkg/terraformer/raw_state.go
  pkg/terraformer/terraform_test.go
  pkg/terraformer/terraformer.go
  pkg/terraformer/types.go
Labels: needs/ok-to-test

#504 [rel-v1.0] Use MTU of 1460 for all SUSE nodes
  controllers/networking-calico/docs/usage-as-end-user.md
  controllers/os-suse-jeos/pkg/generator/templates/cloud-init/suse-jeos.template
  controllers/os-suse-jeos/pkg/generator/templates/script/suse-jeos.template
  controllers/os-suse-jeos/pkg/generator/testfiles/cloud-init/cloud-init
  controllers/os-suse-jeos/pkg/generator/testfiles/script/cloud-init
Labels: needs/ok-to-test

#503 Bumped OpenStack CCM to v1.17.0
  controllers/provider-openstack/charts/images.yaml
Labels: needs/ok-to-test

#502 feat: configure shoot worker node calico port mtu
  controllers/networking-calico/charts/internal/calico/templates/node/configmap-calico-config.yaml
  controllers/networking-calico/charts/internal/calico/values.yaml
  controllers/networking-calico/docs/usage-as-end-user.md
  controllers/networking-calico/hack/api-reference/calico.md
  controllers/networking-calico/pkg/apis/calico/types_network.go
  controllers/networking-calico/pkg/apis/calico/v1alpha1/types_network.go
  controllers/networking-calico/pkg/apis/calico/v1alpha1/zz_generated.conversion.go
  controllers/networking-calico/pkg/apis/calico/v1alpha1/zz_generated.deepcopy.go
  controllers/networking-calico/pkg/apis/calico/zz_generated.deepcopy.go
  controllers/networking-calico/pkg/charts/charts_test.go
  controllers/networking-calico/pkg/charts/utils.go
Labels: needs/ok-to-test

#508 Minor nit in error message
  pkg/controller/worker/genericactuator/machine_controller_manager.go
Labels: needs/ok-to-test

#507 [ci:component:github.com/gardener/cert-management:v0.2.10->v0.2.11]
  controllers/extension-shoot-cert-service/charts/images.yaml
Labels: needs/ok-to-test

#499 Azure: Optimize infrastructure creation/deletion
  controllers/provider-azure/charts/internal/azure-infra/templates/main.tf
Labels: needs/ok-to-test, platform/az

#513 [ci:component:github.com/gardener/cert-management:v0.2.11->v0.2.13]
  controllers/extension-shoot-cert-service/charts/images.yaml
Labels: needs/ok-to-test

#498 Azure: Add storage class for Azure Disk Standard SSD LRS
  controllers/provider-azure/charts/internal/shoot-storageclasses/templates/azure-disk-premium-lrs-storageclass.yaml
  controllers/provider-azure/charts/internal/shoot-storageclasses/templates/azure-disk-standard-lrs-storageclass.yaml
  controllers/provider-azure/charts/internal/shoot-storageclasses/templates/azure-disk-standard-ssd-lrs-storageclass.yaml
  controllers/provider-azure/charts/internal/shoot-storageclasses/templates/azure-file-rbac.yaml
  controllers/provider-azure/charts/internal/shoot-storageclasses/templates/azure-file-standard-lrs-storageclass.yaml
  controllers/provider-azure/charts/internal/shoot-storageclasses/templates/default-storageclass.yaml
  controllers/provider-azure/charts/internal/shoot-storageclasses/templates/storageclasses.yaml
Labels: needs/ok-to-test

#516 Clean up deprecated funcs from pkg/terraformer
  pkg/terraformer/config.go
  pkg/terraformer/terraformer.go
  pkg/terraformer/types.go
  pkg/terraformer/waiter.go
Labels: needs/ok-to-test

#517 Certificate extension copes with no DNS shoots
  controllers/extension-shoot-cert-service/pkg/controller/actuator.go
Labels: needs/ok-to-test
