Repository gardener/gardener-extensions, pull requests merged in 2019-09, with the labels that each got.

#300 Do not add GCP backup secret if not configured
  controllers/provider-gcp/pkg/webhook/controlplanebackup/ensurer.go
Labels: needs/ok-to-test

#302 Put finalizer on referred secret by backup resources
  pkg/controller/backupbucket/reconciler.go
  pkg/controller/backupentry/reconciler.go
Labels: needs/ok-to-test

#303 [fix] Ignore us-east-1 location constraint in backup bucket creation
  controllers/provider-aws/pkg/aws/client/client.go
Labels: reviewed/ok-to-test

#299 Add extension controllers monitoring configuration
  controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/mcm-monitoring-dashboard.json
  controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  controllers/provider-alicloud/charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/ccm-monitoring-dashboard.json
  controllers/provider-alicloud/charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/templates/configmap-monitoring.yaml
  controllers/provider-alicloud/pkg/alicloud/types.go
  controllers/provider-alicloud/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-alicloud/pkg/controller/worker/machine_controller_manager.go
  controllers/provider-aws/charts/internal/cloud-controller-manager/ccm-monitoring-dashboard.json
  controllers/provider-aws/charts/internal/cloud-controller-manager/templates/configmap-monitoring.yaml
  controllers/provider-aws/charts/internal/machine-controller-manager/seed/mcm-monitoring-dashboard.json
  controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  controllers/provider-aws/pkg/aws/types.go
  controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-aws/pkg/controller/worker/machine_controller_manager.go
  controllers/provider-azure/charts/internal/cloud-controller-manager/ccm-monitoring-dashboard.json
  controllers/provider-azure/charts/internal/cloud-controller-manager/templates/configmap-monitoring.yaml
  controllers/provider-azure/charts/internal/machine-controller-manager/seed/mcm-monitoring-dashboard.json
  controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  controllers/provider-azure/pkg/azure/types.go
  controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-azure/pkg/controller/worker/machine_controller_manager.go
  controllers/provider-gcp/charts/internal/cloud-controller-manager/ccm-monitoring-dashboard.json
  controllers/provider-gcp/charts/internal/cloud-controller-manager/templates/configmap-monitoring.yaml
  controllers/provider-gcp/charts/internal/machine-controller-manager/seed/mcm-monitoring-dashboard.json
  controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  controllers/provider-gcp/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-gcp/pkg/controller/worker/machine_controller_manager.go
  controllers/provider-gcp/pkg/gcp/types.go
  controllers/provider-openstack/charts/internal/cloud-controller-manager/ccm-monitoring-dashboard.json
  controllers/provider-openstack/charts/internal/cloud-controller-manager/templates/configmap-monitoring.yaml
  controllers/provider-openstack/charts/internal/machine-controller-manager/seed/mcm-monitoring-dashboard.json
  controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  controllers/provider-openstack/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-openstack/pkg/controller/worker/machine_controller_manager.go
  controllers/provider-openstack/pkg/openstack/types.go
  controllers/provider-packet/charts/internal/machine-controller-manager/seed/mcm-monitoring-dashboard.json
  controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  controllers/provider-packet/charts/internal/seed-controlplane/charts/packet-cloud-controller-manager/ccm-monitoring-dashboard.json
  controllers/provider-packet/charts/internal/seed-controlplane/charts/packet-cloud-controller-manager/templates/configmap-monitoring.yaml
  controllers/provider-packet/charts/internal/seed-controlplane/charts/packet-cloud-controller-manager/values.yaml
  controllers/provider-packet/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-packet/pkg/controller/worker/machine_controller_manager.go
  controllers/provider-packet/pkg/packet/types.go
Labels: needs/ok-to-test

#304 [ci:component:github.com/gardener/etcd-backup-restore:0.7.1->0.7.2]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: reviewed/ok-to-test

#305 Clean tools.go
  go.mod
  hack/tools.go
Labels: needs/ok-to-test

#307 [ci:component:github.com/gardener/etcd-backup-restore:0.7.2->0.7.3]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: needs/ok-to-test

#306 Add missing example and test files for shoot-dns-service
  controllers/extension-shoot-dns-service/example/11-resource-manager-shoot.yaml
  controllers/extension-shoot-dns-service/example/12-resource-manager-seed.yaml
  controllers/extension-shoot-dns-service/example/40-source-service-shoot.yaml
  controllers/extension-shoot-dns-service/example/kubeconfig
  controllers/extension-shoot-dns-service/hack/shoot-apiserver-access
  controllers/extension-shoot-dns-service/hack/shoot-apply-service-with-dnsnames
Labels: needs/ok-to-test

#308 Fix alicloud backupentry deletion
  README.md
  controllers/provider-alicloud/pkg/alicloud/client/client.go
Labels: needs/ok-to-test

#246 Azure: Move to standard loadbalancer
  controllers/provider-azure/charts/internal/cloud-provider-config/templates/cloud-provider-config.tpl
  controllers/provider-azure/charts/internal/cloud-provider-config/values.yaml
  controllers/provider-azure/docs/migrate-loadbalancer.md
  controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-azure/pkg/controller/controlplane/valuesprovider_test.go
Labels: needs/ok-to-test, platform/az

#311 Update golangci-lint to v1.18.0
  hack/install-requirements.sh
Labels: needs/ok-to-test

#290 Add URN field
  controllers/provider-azure/charts/internal/machineclass/templates/machineclass.yaml
  controllers/provider-azure/charts/internal/machineclass/values.yaml
  controllers/provider-azure/charts/provider-azure/values.yaml
  controllers/provider-azure/example/00-componentconfig.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-azure/pkg/apis/azure/helper/helper_test.go
  controllers/provider-azure/pkg/apis/azure/types_worker.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/types_worker.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/zz_generated.conversion.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-azure/pkg/apis/azure/zz_generated.deepcopy.go
  controllers/provider-azure/pkg/apis/config/helper/helper_test.go
  controllers/provider-azure/pkg/apis/config/types.go
  controllers/provider-azure/pkg/apis/config/v1alpha1/types.go
  controllers/provider-azure/pkg/apis/config/v1alpha1/zz_generated.conversion.go
  controllers/provider-azure/pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-azure/pkg/apis/config/zz_generated.deepcopy.go
  controllers/provider-azure/pkg/controller/worker/machine_images.go
  controllers/provider-azure/pkg/controller/worker/machines.go
  controllers/provider-azure/pkg/controller/worker/machines_test.go
Labels: needs/ok-to-test

#310 Enable customized images for AliCloud
  controllers/provider-alicloud/charts/provider-alicloud/values.yaml
  controllers/provider-alicloud/example/00-componentconfig.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-alicloud/pkg/apis/alicloud/helper/helper.go
  controllers/provider-alicloud/pkg/apis/alicloud/types_worker.go
  controllers/provider-alicloud/pkg/apis/config/helper/helper.go
  controllers/provider-alicloud/pkg/apis/config/helper/helper_test.go
  controllers/provider-alicloud/pkg/apis/config/types.go
  controllers/provider-alicloud/pkg/apis/config/v1alpha1/types.go
  controllers/provider-alicloud/pkg/apis/config/v1alpha1/zz_generated.conversion.go
  controllers/provider-alicloud/pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-alicloud/pkg/apis/config/zz_generated.deepcopy.go
  controllers/provider-alicloud/pkg/controller/worker/machine_images.go
  controllers/provider-alicloud/pkg/controller/worker/machines.go
  controllers/provider-alicloud/pkg/controller/worker/machines_test.go
Labels: needs/ok-to-test

#321 BackupEntry generic actuator handles terminating namespaces
  pkg/controller/backupentry/genericactuator/actuator.go
Labels: reviewed/ok-to-test

#312 Update calico to v3.8.2
  controllers/networking-calico/charts/images.yaml
  controllers/networking-calico/charts/internal/calico/templates/calico.yaml
  controllers/networking-calico/charts/internal/calico/templates/config.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-psp.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-horizontal-autoscaler-clusterrole.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-horizontal-autoscaler-clusterrolebinding.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-horizontal-autoscaler-psp.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-vertical-autoscaler-clusterrole.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-vertical-autoscaler-clusterrolebinding.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-vertical-autoscaler-psp.yaml
  controllers/networking-calico/charts/internal/calico/templates/rbac.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-horizontal-autoscaling-config.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-vertical-autoscaling-config.yaml
  controllers/networking-calico/charts/internal/calico/values.yaml
  controllers/networking-calico/charts/networking-calico/values.yaml
  controllers/networking-calico/example/controller-registration.yaml
  controllers/networking-calico/pkg/calico/types.go
  controllers/networking-calico/pkg/charts/charts_test.go
  controllers/networking-calico/pkg/charts/utils.go
  controllers/networking-calico/pkg/imagevector/imagevector.go
Labels: needs/ok-to-test

#322 Control plane generic actuator waits for managed resources to be deleted
  go.sum
  pkg/controller/controlplane/genericactuator/actuator.go
  pkg/controller/controlplane/genericactuator/actuator_test.go
  pkg/controller/managedresources.go
  pkg/controller/utils.go
Labels: needs/ok-to-test

#324 [ci:component:github.com/gardener/machine-controller-manager:0.21.1->0.22.0]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: needs/ok-to-test

#325 [ci:component:github.com/gardener/terraformer:0.13.0->0.14.0]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: needs/ok-to-test

#330 Replace deprecated field in alicloud provider
  controllers/provider-alicloud/charts/internal/alicloud-infra/templates/main.tf
Labels: needs/ok-to-test

#328 Wait until managed resources are deleted
  controllers/extension-certificate-service/pkg/controller/certservice/actuator.go
  controllers/extension-shoot-dns-service/pkg/controller/actuator.go
  controllers/networking-calico/pkg/controller/actuator_delete.go
  pkg/controller/worker/genericactuator/machine_controller_manager.go
Labels: needs/ok-to-test

#331 Azure: Update deprecated terraform resources
  controllers/provider-azure/charts/internal/azure-infra/templates/main.tf
Labels: needs/ok-to-test, platform/az

#333 remove replicase field to enable autoscaling
  controllers/networking-calico/charts/internal/calico/templates/calico.yaml
Labels: needs/ok-to-test

#338 [ci:component:github.com/gardener/terraformer:0.14.0->0.15.0]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: needs/ok-to-test

#332 Azure: Allow to configure service endpoints
  controllers/provider-azure/charts/internal/azure-infra/templates/main.tf
  controllers/provider-azure/charts/internal/azure-infra/values.yaml
  controllers/provider-azure/pkg/apis/azure/types_infrastructure.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/types_infrastructure.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/zz_generated.conversion.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-azure/pkg/apis/azure/zz_generated.deepcopy.go
  controllers/provider-azure/pkg/internal/infrastructure/terraform.go
  controllers/provider-azure/pkg/internal/infrastructure/terraform_test.go
Labels: needs/ok-to-test, platform/az

#327 Azure: Support for Availability zones
  controllers/provider-azure/charts/images.yaml
  controllers/provider-azure/charts/internal/azure-infra/templates/main.tf
  controllers/provider-azure/charts/internal/azure-infra/values.yaml
  controllers/provider-azure/charts/internal/cloud-provider-config/templates/cloud-provider-config.tpl
  controllers/provider-azure/charts/internal/cloud-provider-config/values.yaml
  controllers/provider-azure/charts/internal/machineclass/templates/machineclass.yaml
  controllers/provider-azure/charts/internal/machineclass/values.yaml
  controllers/provider-azure/pkg/apis/azure/types_infrastructure.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/types_infrastructure.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/zz_generated.conversion.go
  controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-azure/pkg/controller/controlplane/valuesprovider_test.go
  controllers/provider-azure/pkg/controller/worker/machines.go
  controllers/provider-azure/pkg/internal/infrastructure/terraform.go
  controllers/provider-azure/pkg/internal/infrastructure/terraform_test.go
Labels: needs/ok-to-test, platform/az

#336 Prepare provider-aws to terraform v0.12
  controllers/provider-aws/charts/internal/aws-infra/templates/main.tf
Labels: needs/ok-to-test, platform/aws

#339 fix update strategy for calico-typha deployment
  controllers/networking-calico/charts/internal/calico/templates/calico.yaml
Labels: needs/ok-to-test

#340 Create awsClient when required
  controllers/provider-aws/pkg/controller/infrastructure/actuator_reconcile.go
Labels: needs/ok-to-test

#342 Fix calico chart to work when privileged containers are not allowed
  controllers/networking-calico/charts/internal/calico/templates/calico.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-psp.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-horizontal-autoscaler-psp.yaml
Labels: needs/ok-to-test

#337 Randomise etcd backup schedule per shoot
  controllers/provider-alicloud/charts/provider-alicloud/templates/configmap.yaml
  controllers/provider-alicloud/charts/provider-alicloud/values.yaml
  controllers/provider-alicloud/example/00-componentconfig.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-alicloud/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-alicloud/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-aws/charts/provider-aws/templates/configmap.yaml
  controllers/provider-aws/charts/provider-aws/values.yaml
  controllers/provider-aws/example/00-componentconfig.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-aws/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-aws/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-azure/charts/provider-azure/templates/configmap.yaml
  controllers/provider-azure/charts/provider-azure/values.yaml
  controllers/provider-azure/example/00-componentconfig.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-azure/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-azure/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-gcp/charts/provider-gcp/templates/configmap.yaml
  controllers/provider-gcp/charts/provider-gcp/values.yaml
  controllers/provider-gcp/example/00-componentconfig.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-gcp/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-gcp/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-openstack/charts/provider-openstack/templates/configmap.yaml
  controllers/provider-openstack/charts/provider-openstack/values.yaml
  controllers/provider-openstack/example/00-componentconfig.yaml
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-openstack/pkg/webhook/controlplanebackup/ensurer.go
  controllers/provider-openstack/pkg/webhook/controlplanebackup/ensurer_test.go
  controllers/provider-packet/pkg/webhook/controlplanebackup/ensurer_test.go
  go.sum
  pkg/webhook/controlplane/etcd.go
  vendor/k8s.io/gengo/args/args.go
  vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
  vendor/k8s.io/gengo/examples/set-gen/sets/string.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/parser/parse.go
  vendor/modules.txt
Labels: needs/ok-to-test

#326 Changing limits for backup-restore container
  controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  pkg/webhook/controlplane/etcd.go
Labels: needs/ok-to-test

#344 Change monitoring ConfigMaps' syntax of provider-specific components
  controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  controllers/provider-alicloud/charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/templates/configmap-monitoring.yaml
  controllers/provider-aws/charts/internal/cloud-controller-manager/templates/configmap-monitoring.yaml
  controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  controllers/provider-azure/charts/internal/cloud-controller-manager/templates/configmap-monitoring.yaml
  controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  controllers/provider-gcp/charts/internal/cloud-controller-manager/templates/configmap-monitoring.yaml
  controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  controllers/provider-openstack/charts/internal/cloud-controller-manager/templates/configmap-monitoring.yaml
  controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  controllers/provider-packet/charts/internal/seed-controlplane/charts/packet-cloud-controller-manager/templates/configmap-monitoring.yaml
Labels: needs/ok-to-test
