Repository gardener/gardener-extensions, pull requests merged in 2019-11, with the labels that each got.

#404 Vendor gardener/gardener@2bcc57c0519b
  Dockerfile
  go.mod
  go.sum
  vendor/github.com/Masterminds/sprig/.travis.yml
  vendor/github.com/Masterminds/sprig/CHANGELOG.md
  vendor/github.com/Masterminds/sprig/crypto.go
  vendor/github.com/Masterminds/sprig/dict.go
  vendor/github.com/Masterminds/sprig/functions.go
  vendor/github.com/Masterminds/sprig/glide.lock
  vendor/github.com/Masterminds/sprig/glide.yaml
  vendor/github.com/Masterminds/sprig/list.go
  vendor/github.com/Masterminds/sprig/network.go
  vendor/github.com/Masterminds/sprig/numeric.go
  vendor/github.com/Masterminds/sprig/url.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/reconcile/conditions/conditions.go
  vendor/github.com/gardener/controller-manager-library/pkg/fieldpath/compile.go
  vendor/github.com/gardener/controller-manager-library/pkg/fieldpath/nodes.go
  vendor/github.com/gardener/controller-manager-library/pkg/resources/mod.go
  vendor/github.com/gardener/controller-manager-library/pkg/resources/slavecache.go
  vendor/github.com/gardener/controller-manager-library/pkg/resources/subcache.go
  vendor/github.com/gardener/controller-manager-library/pkg/utils/types.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/garden/types.go
  vendor/github.com/gardener/gardener/pkg/apis/garden/v1beta1/types.go
  vendor/github.com/gardener/gardener/pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/garden/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/operation/common/types.go
  vendor/github.com/gardener/gardener/pkg/operation/common/utils.go
  vendor/github.com/gardener/gardener/pkg/operation/terraformer/errors.go
  vendor/github.com/gardener/gardener/pkg/operation/terraformer/terraformer.go
  vendor/github.com/gardener/gardener/pkg/operation/terraformer/types.go
  vendor/github.com/mitchellh/copystructure/.travis.yml
  vendor/github.com/mitchellh/copystructure/LICENSE
  vendor/github.com/mitchellh/copystructure/README.md
  vendor/github.com/mitchellh/copystructure/copier_time.go
  vendor/github.com/mitchellh/copystructure/copystructure.go
  vendor/github.com/mitchellh/copystructure/go.mod
  vendor/github.com/mitchellh/copystructure/go.sum
  vendor/github.com/mitchellh/reflectwalk/.travis.yml
  vendor/github.com/mitchellh/reflectwalk/LICENSE
  vendor/github.com/mitchellh/reflectwalk/README.md
  vendor/github.com/mitchellh/reflectwalk/go.mod
  vendor/github.com/mitchellh/reflectwalk/location.go
  vendor/github.com/mitchellh/reflectwalk/location_string.go
  vendor/github.com/mitchellh/reflectwalk/reflectwalk.go
  vendor/modules.txt
Labels: needs/ok-to-test

#405 Revert GCP CloudNat
  controllers/provider-gcp/charts/internal/gcp-infra/templates/main.tf
  controllers/provider-gcp/charts/internal/gcp-infra/values.yaml
  controllers/provider-gcp/charts/internal/machineclass/values.yaml
  controllers/provider-gcp/pkg/controller/worker/machines.go
  controllers/provider-gcp/pkg/controller/worker/machines_test.go
  controllers/provider-gcp/pkg/internal/infrastructure/terraform.go
  controllers/provider-gcp/pkg/internal/infrastructure/terraform_test.go
Labels: needs/ok-to-test

#397 Enhance imagevector overwrite for shoot-dns-service
  controllers/extension-shoot-dns-service/charts/extension-shoot-dns-service/templates/configmap-imagevector-overwrite.yaml
  controllers/extension-shoot-dns-service/charts/extension-shoot-dns-service/templates/deployment.yaml
  controllers/extension-shoot-dns-service/charts/extension-shoot-dns-service/values.yaml
  controllers/extension-shoot-dns-service/example/controller-registration.yaml
Labels: needs/ok-to-test

#416 Azure: Fix end-user documentation
  controllers/provider-azure/docs/usage-as-end-user.md
Labels: needs/ok-to-test, platform/az

#414 Enforce type information for actuators
  controllers/extension-certificate-service/pkg/controller/certservice/add.go
  controllers/extension-shoot-cert-service/pkg/controller/add.go
  controllers/extension-shoot-dns-service/pkg/controller/add.go
  controllers/networking-calico/pkg/controller/add.go
  controllers/os-coreos-alicloud/pkg/coreos-alicloud/add.go
  controllers/os-coreos/pkg/coreos/add.go
  controllers/provider-alicloud/pkg/controller/backupbucket/add.go
  controllers/provider-alicloud/pkg/controller/backupentry/add.go
  controllers/provider-alicloud/pkg/controller/controlplane/add.go
  controllers/provider-alicloud/pkg/controller/infrastructure/add.go
  controllers/provider-alicloud/pkg/controller/worker/add.go
  controllers/provider-aws/pkg/controller/backupbucket/add.go
  controllers/provider-aws/pkg/controller/backupentry/add.go
  controllers/provider-aws/pkg/controller/controlplane/add.go
  controllers/provider-aws/pkg/controller/infrastructure/add.go
  controllers/provider-aws/pkg/controller/worker/add.go
  controllers/provider-azure/pkg/controller/backupbucket/add.go
  controllers/provider-azure/pkg/controller/backupentry/add.go
  controllers/provider-azure/pkg/controller/controlplane/add.go
  controllers/provider-azure/pkg/controller/infrastructure/add.go
  controllers/provider-azure/pkg/controller/worker/add.go
  controllers/provider-gcp/pkg/controller/backupbucket/add.go
  controllers/provider-gcp/pkg/controller/backupentry/add.go
  controllers/provider-gcp/pkg/controller/controlplane/add.go
  controllers/provider-gcp/pkg/controller/infrastructure/add.go
  controllers/provider-gcp/pkg/controller/worker/add.go
  controllers/provider-openstack/pkg/controller/backupbucket/add.go
  controllers/provider-openstack/pkg/controller/backupentry/add.go
  controllers/provider-openstack/pkg/controller/controlplane/add.go
  controllers/provider-openstack/pkg/controller/infrastructure/add.go
  controllers/provider-openstack/pkg/controller/worker/add.go
  controllers/provider-packet/pkg/controller/controlplane/add.go
  controllers/provider-packet/pkg/controller/infrastructure/add.go
  controllers/provider-packet/pkg/controller/worker/add.go
  pkg/controller/backupbucket/controller.go
  pkg/controller/backupentry/controller.go
  pkg/controller/controlplane/controller.go
  pkg/controller/extension/reconciler.go
  pkg/controller/infrastructure/controller.go
  pkg/controller/network/controller.go
  pkg/controller/operatingsystemconfig/controller.go
  pkg/controller/operatingsystemconfig/oscommon/add.go
  pkg/controller/worker/controller.go
  pkg/predicate/predicate.go
Labels: needs/ok-to-test

#415 OpenStack: set the "default" name for a default storage class
  controllers/provider-openstack/charts/internal/shoot-storageclasses/templates/storageclasses.yaml
Labels: needs/ok-to-test

#401 Azure: Enable os disk configuration
  controllers/provider-azure/charts/internal/machineclass/templates/machineclass.yaml
  controllers/provider-azure/charts/internal/machineclass/values.yaml
  controllers/provider-azure/docs/usage-as-end-user.md
  controllers/provider-azure/docs/usage-as-operator.md
  controllers/provider-azure/pkg/controller/worker/machines.go
  controllers/provider-azure/pkg/controller/worker/machines_test.go
Labels: needs/ok-to-test, platform/az

#419 up the requested resources so it won't crash
  controllers/provider-aws/charts/internal/aws-lb-readvertiser/templates/aws-lb-readvertiser.yaml
Labels: needs/ok-to-test

#400 JeOS: ensure required packages are installed
  controllers/os-suse-jeos/pkg/generator/templates/cloud-init-suse-jeos.template
  controllers/os-suse-jeos/pkg/generator/testfiles/cloud-init
Labels: needs/ok-to-test, status/under-investigation, topology/shoot

#418 Move terraformer library from gardener to gardener-extensions
  controllers/provider-alicloud/pkg/controller/common/terraform.go
  controllers/provider-alicloud/pkg/controller/common/terraform_test.go
  controllers/provider-alicloud/pkg/controller/infrastructure/actuator.go
  controllers/provider-alicloud/pkg/controller/infrastructure/actuator_test.go
  controllers/provider-aws/pkg/controller/infrastructure/actuator.go
  controllers/provider-aws/pkg/controller/infrastructure/actuator_delete.go
  controllers/provider-aws/pkg/controller/infrastructure/actuator_reconcile.go
  controllers/provider-azure/pkg/controller/infrastructure/actuator.go
  controllers/provider-azure/pkg/controller/infrastructure/actuator_reconcile.go
  controllers/provider-azure/pkg/internal/infrastructure/terraform.go
  controllers/provider-azure/pkg/internal/terraform.go
  controllers/provider-gcp/pkg/controller/infrastructure/actuator.go
  controllers/provider-gcp/pkg/controller/infrastructure/actuator_delete.go
  controllers/provider-gcp/pkg/controller/infrastructure/actuator_reconcile.go
  controllers/provider-gcp/pkg/internal/infrastructure/terraform.go
  controllers/provider-gcp/pkg/internal/terraform.go
  controllers/provider-openstack/pkg/controller/infrastructure/actuator.go
  controllers/provider-openstack/pkg/controller/infrastructure/actuator_reconcile.go
  controllers/provider-openstack/pkg/internal/infrastructure/terraform.go
  controllers/provider-openstack/pkg/internal/terraform.go
  controllers/provider-packet/pkg/controller/infrastructure/actuator.go
  controllers/provider-packet/pkg/controller/infrastructure/actuator_reconcile.go
  pkg/gardener/terraformer/terraformer.go
  pkg/gardener/terraformer/types.go
  pkg/mock/gardener-extensions/terraformer/doc.go
  pkg/mock/gardener-extensions/terraformer/mocks.go
  pkg/terraformer/config.go
  pkg/terraformer/errors.go
  pkg/terraformer/errors_test.go
  pkg/terraformer/state.go
  pkg/terraformer/terraform_test.go
  pkg/terraformer/terraformer.go
  pkg/terraformer/terraformer_suite_test.go
  pkg/terraformer/types.go
  pkg/terraformer/waiter.go
  vendor/modules.txt
Labels: needs/ok-to-test

#297 Generate bootstrap script from OSC for JeOS
  controllers/os-suse-jeos/charts/os-suse-jeos/templates/deployment.yaml
  controllers/os-suse-jeos/charts/os-suse-jeos/values.yaml
  controllers/os-suse-jeos/example/controller-registration-local.yaml
  controllers/os-suse-jeos/example/controller-registration.yaml
  controllers/os-suse-jeos/pkg/generator/cloudinit_test.go
  controllers/os-suse-jeos/pkg/generator/generator.go
  controllers/os-suse-jeos/pkg/generator/invalid_config_test.go
  controllers/os-suse-jeos/pkg/generator/script_test.go
  controllers/os-suse-jeos/pkg/generator/templates/cloud-init/suse-jeos.template
  controllers/os-suse-jeos/pkg/generator/templates/script/suse-jeos.template
  controllers/os-suse-jeos/pkg/generator/testfiles/cloud-init/cloud-init
  controllers/os-suse-jeos/pkg/generator/testfiles/script/cloud-init
Labels: kind/enhancement, reviewed/lgtm, topology/shoot

#420 ensure secrets finalizers are accessible otherwise operatingsystemconfigs can use secrets as owner
  controllers/os-coreos-alicloud/charts/os-coreos-alicloud/templates/rbac.yaml
  controllers/os-coreos-alicloud/example/controller-registration.yaml
  controllers/os-coreos/charts/os-coreos/templates/rbac.yaml
  controllers/os-coreos/example/controller-registration.yaml
  controllers/os-suse-jeos/charts/os-suse-jeos/templates/rbac.yaml
  controllers/os-suse-jeos/example/controller-registration.yaml
  controllers/os-ubuntu-alicloud/charts/os-ubuntu-alicloud/templates/rbac.yaml
  controllers/os-ubuntu-alicloud/example/controller-registration.yaml
  controllers/os-ubuntu/charts/os-ubuntu/templates/rbac.yaml
  controllers/os-ubuntu/example/controller-registration.yaml
Labels: needs/ok-to-test

#423 Use defaults for env vars
  controllers/os-suse-jeos/pkg/generator/generator.go
  controllers/os-suse-jeos/pkg/generator/invalid_config_test.go
Labels: kind/bug, needs/ok-to-test

#425 Restrict terraformer to delete jobs and pods only in its namespace
  pkg/terraformer/terraformer.go
Labels: kind/bug, needs/ok-to-test

#422 add role to allow bootstrap token creation in the kube-system namespce of the shoot by MCM
  controllers/provider-alicloud/charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml
  controllers/provider-alicloud/charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml
  controllers/provider-aws/charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml
  controllers/provider-aws/charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml
  controllers/provider-azure/charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml
  controllers/provider-azure/charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml
  controllers/provider-gcp/charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml
  controllers/provider-gcp/charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml
  controllers/provider-openstack/charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml
  controllers/provider-openstack/charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml
  controllers/provider-packet/charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml
  controllers/provider-packet/charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml
Labels: needs/ok-to-test

#417 Enable Quota friendly Cloud Router sharing for CloudNATs
  controllers/provider-gcp/charts/internal/gcp-infra/templates/main.tf
  controllers/provider-gcp/charts/internal/gcp-infra/values.yaml
  controllers/provider-gcp/charts/internal/machineclass/values.yaml
  controllers/provider-gcp/docs/usage-as-end-user.md
  controllers/provider-gcp/example/30-infrastructure.yaml
  controllers/provider-gcp/hack/api-reference/api.md
  controllers/provider-gcp/pkg/apis/gcp/types_infrastructure.go
  controllers/provider-gcp/pkg/apis/gcp/v1alpha1/types_infrastructure.go
  controllers/provider-gcp/pkg/apis/gcp/v1alpha1/zz_generated.conversion.go
  controllers/provider-gcp/pkg/apis/gcp/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-gcp/pkg/apis/gcp/validation/infrastructure.go
  controllers/provider-gcp/pkg/apis/gcp/validation/infrastructure_test.go
  controllers/provider-gcp/pkg/apis/gcp/zz_generated.deepcopy.go
  controllers/provider-gcp/pkg/controller/worker/machines.go
  controllers/provider-gcp/pkg/controller/worker/machines_test.go
  controllers/provider-gcp/pkg/internal/infrastructure/terraform.go
  controllers/provider-gcp/pkg/internal/infrastructure/terraform_test.go
Labels: needs/ok-to-test

#421 Remove deprecated fields
  controllers/provider-azure/charts/internal/machineclass/templates/machineclass.yaml
  controllers/provider-azure/charts/internal/machineclass/values.yaml
  controllers/provider-azure/charts/provider-azure/values.yaml
  controllers/provider-azure/docs/usage-as-operator.md
  controllers/provider-azure/example/00-componentconfig.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-azure/hack/api-reference/api.md
  controllers/provider-azure/hack/api-reference/config.md
  controllers/provider-azure/pkg/apis/azure/helper/helper_test.go
  controllers/provider-azure/pkg/apis/azure/types_worker.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/types_worker.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/zz_generated.conversion.go
  controllers/provider-azure/pkg/apis/config/helper/helper_test.go
  controllers/provider-azure/pkg/apis/config/types.go
  controllers/provider-azure/pkg/apis/config/v1alpha1/types.go
  controllers/provider-azure/pkg/apis/config/v1alpha1/zz_generated.conversion.go
  controllers/provider-azure/pkg/controller/worker/machine_images.go
  controllers/provider-azure/pkg/controller/worker/machines.go
  controllers/provider-azure/pkg/controller/worker/machines_test.go
Labels: needs/ok-to-test

#433 Set dns-controller-manager version to 0.7.2
  controllers/extension-shoot-dns-service/charts/images.yaml
Labels: needs/ok-to-test

#429 [ci:component:github.com/gardener/cert-management:0.2.5->0.2.6]
  controllers/extension-shoot-cert-service/charts/images.yaml
Labels: needs/ok-to-test

#431 bastion host related ssh rules removed
  controllers/provider-aws/charts/internal/aws-infra/templates/main.tf
Labels: needs/ok-to-test

#435 [release-0.14] Vendor gardener/gardener@dbaaea7ad82b
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/pkg/operation/terraformer/terraformer.go
  vendor/github.com/gardener/gardener/test/integration/framework/common.go
  vendor/github.com/mitchellh/copystructure/README.md
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test

#426 Switch from job to pod for terraform apply/destroy
  controllers/provider-alicloud/pkg/controller/common/terraform.go
  controllers/provider-alicloud/pkg/controller/common/terraform_test.go
  controllers/provider-alicloud/pkg/controller/infrastructure/actuator_test.go
  controllers/provider-aws/pkg/controller/infrastructure/actuator.go
  controllers/provider-azure/pkg/internal/terraform.go
  controllers/provider-gcp/pkg/internal/terraform.go
  controllers/provider-openstack/pkg/internal/terraform.go
  controllers/provider-packet/pkg/controller/infrastructure/actuator.go
  pkg/mock/gardener-extensions/terraformer/mocks.go
  pkg/terraformer/config.go
  pkg/terraformer/state.go
  pkg/terraformer/terraform_test.go
  pkg/terraformer/terraformer.go
  pkg/terraformer/types.go
  pkg/terraformer/waiter.go
Labels: kind/bug, needs/ok-to-test

#437 Pass LastUpdateTime to LastErrors
  Dockerfile
  pkg/controller/status.go
Labels: needs/ok-to-test

#432 Provide option to disable calico-typha
  controllers/networking-calico/charts/internal/calico/templates/calico-typha.yaml
  controllers/networking-calico/charts/internal/calico/templates/calico.yaml
  controllers/networking-calico/charts/internal/calico/templates/config.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-clusterrole.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-clusterrolebinding.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-kube-controllers-clusterrole.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-kube-controllers-clusterrolebinding.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-kube-controllers-psp.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-psp.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-clusterrole.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-clusterrolebinding.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-horizontal-autoscaler-clusterrole.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-horizontal-autoscaler-clusterrolebinding.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-horizontal-autoscaler-psp.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-psp.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-vertical-autoscaler-clusterrole.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-vertical-autoscaler-clusterrolebinding.yaml
  controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-vertical-autoscaler-psp.yaml
  controllers/networking-calico/charts/internal/calico/templates/rbac.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-horizontal-autoscaling-config.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-vertical-autoscaling-config.yaml
  controllers/networking-calico/charts/internal/calico/values.yaml
  controllers/networking-calico/docs/usage-as-end-user.md
  controllers/networking-calico/example/20-network.yaml
  controllers/networking-calico/hack/api-reference/calico.md
  controllers/networking-calico/pkg/apis/calico/types_network.go
  controllers/networking-calico/pkg/apis/calico/v1alpha1/types_network.go
  controllers/networking-calico/pkg/apis/calico/v1alpha1/zz_generated.conversion.go
  controllers/networking-calico/pkg/apis/calico/v1alpha1/zz_generated.deepcopy.go
  controllers/networking-calico/pkg/apis/calico/zz_generated.deepcopy.go
  controllers/networking-calico/pkg/charts/charts_test.go
  controllers/networking-calico/pkg/charts/utils.go
  controllers/provider-alicloud/docs/usage-as-end-user.md
  controllers/provider-aws/docs/usage-as-end-user.md
  controllers/provider-azure/docs/usage-as-end-user.md
  controllers/provider-gcp/docs/usage-as-end-user.md
  controllers/provider-openstack/docs/usage-as-end-user.md
  hack/check.sh
Labels: needs/ok-to-test

#436 Fix defaulting for storage classes
  pkg/controller/controlplane/genericactuator/actuator.go
  pkg/controller/controlplane/genericactuator/actuator_test.go
  pkg/controller/managedresources.go
  pkg/controller/worker/genericactuator/machine_controller_manager.go
Labels: needs/ok-to-test

#442 [ci:component:github.com/gardener/machine-controller-manager:0.23.0->0.24.0]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: needs/ok-to-test

#443 [ci:component:github.com/gardener/cert-management:0.2.6->0.2.7]
  controllers/extension-shoot-cert-service/charts/images.yaml
Labels: needs/ok-to-test

#444 [ci:component:github.com/gardener/cert-management:0.2.7->0.2.8]
  controllers/extension-shoot-cert-service/charts/images.yaml
Labels: needs/ok-to-test

#448 Fix CSI volume security issue on AliCloud for k8s v1.13
  controllers/provider-alicloud/charts/images.yaml
Labels: needs/ok-to-test

#449 Update image version
  Dockerfile
Labels: needs/ok-to-test

#456 Fix typha calico-typha-vertical-autoscaler
  controllers/networking-calico/charts/internal/calico/templates/typha-vertical-autoscaling-config.yaml
Labels: needs/ok-to-test

#457 [release-1.0] Fix typha calico-typha-vertical-autoscaler
  controllers/networking-calico/charts/internal/calico/templates/typha-vertical-autoscaling-config.yaml
Labels: needs/ok-to-test

#450 Expose CloudNAT Minimal Ports per VM
  controllers/provider-gcp/charts/internal/gcp-infra/templates/main.tf
  controllers/provider-gcp/charts/internal/gcp-infra/values.yaml
  controllers/provider-gcp/docs/usage-as-end-user.md
  controllers/provider-gcp/example/30-infrastructure.yaml
  controllers/provider-gcp/hack/api-reference/api.md
  controllers/provider-gcp/pkg/apis/gcp/types_infrastructure.go
  controllers/provider-gcp/pkg/apis/gcp/v1alpha1/types_infrastructure.go
  controllers/provider-gcp/pkg/apis/gcp/v1alpha1/zz_generated.conversion.go
  controllers/provider-gcp/pkg/apis/gcp/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-gcp/pkg/apis/gcp/zz_generated.deepcopy.go
  controllers/provider-gcp/pkg/internal/infrastructure/terraform.go
  controllers/provider-gcp/pkg/internal/infrastructure/terraform_test.go
Labels: needs/ok-to-test

#458 [release-1.0] Expose CloudNAT Minimal Ports per VM
  controllers/provider-gcp/charts/internal/gcp-infra/templates/main.tf
  controllers/provider-gcp/charts/internal/gcp-infra/values.yaml
  controllers/provider-gcp/docs/usage-as-end-user.md
  controllers/provider-gcp/example/30-infrastructure.yaml
  controllers/provider-gcp/hack/api-reference/api.md
  controllers/provider-gcp/pkg/apis/gcp/types_infrastructure.go
  controllers/provider-gcp/pkg/apis/gcp/v1alpha1/types_infrastructure.go
  controllers/provider-gcp/pkg/apis/gcp/v1alpha1/zz_generated.conversion.go
  controllers/provider-gcp/pkg/apis/gcp/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-gcp/pkg/apis/gcp/zz_generated.deepcopy.go
  controllers/provider-gcp/pkg/internal/infrastructure/terraform.go
  controllers/provider-gcp/pkg/internal/infrastructure/terraform_test.go
Labels: needs/ok-to-test

#453 Introduced checksums for shoot controlplane chart values
  controllers/provider-alicloud/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-alicloud/pkg/controller/controlplane/valuesprovider_test.go
  controllers/provider-packet/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-packet/pkg/controller/controlplane/valuesprovider_test.go
  pkg/controller/controlplane/genericactuator/actuator.go
  pkg/controller/controlplane/genericactuator/actuator_test.go
  pkg/controller/controlplane/genericactuator/noopvaluesprovider.go
  pkg/mock/gardener-extensions/controller/controlplane/genericactuator/mocks.go
Labels: needs/ok-to-test

#459 Fix backup entry deletion for provider-aws
  controllers/provider-aws/pkg/aws/client/client.go
Labels: needs/ok-to-test

#467 [ci:component:github.com/gardener/terraformer:0.16.0->0.17.0]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
Labels: needs/ok-to-test

#438 Add AWS validator for core resources
  Makefile
  controllers/hyper/cmd/gardener-extension-hyper/app/app.go
  controllers/provider-aws/charts/validator-aws/.helmignore
  controllers/provider-aws/charts/validator-aws/Chart.yaml
  controllers/provider-aws/charts/validator-aws/charts/application/Chart.yaml
  controllers/provider-aws/charts/validator-aws/charts/application/templates/_helpers.tpl
  controllers/provider-aws/charts/validator-aws/charts/application/templates/rbac.yaml
  controllers/provider-aws/charts/validator-aws/charts/application/templates/serviceaccount.yaml
  controllers/provider-aws/charts/validator-aws/charts/application/templates/validatingwebhook-validator.yaml
  controllers/provider-aws/charts/validator-aws/charts/application/values.yaml
  controllers/provider-aws/charts/validator-aws/charts/runtime/Chart.yaml
  controllers/provider-aws/charts/validator-aws/charts/runtime/templates/_helpers.tpl
  controllers/provider-aws/charts/validator-aws/charts/runtime/templates/deployment.yaml
  controllers/provider-aws/charts/validator-aws/charts/runtime/templates/secret-cert.yaml
  controllers/provider-aws/charts/validator-aws/charts/runtime/templates/secret-kubeconfig.yaml
  controllers/provider-aws/charts/validator-aws/charts/runtime/templates/service.yaml
  controllers/provider-aws/charts/validator-aws/charts/runtime/values.yaml
  controllers/provider-aws/charts/validator-aws/templates/_helpers.tpl
  controllers/provider-aws/charts/validator-aws/values.yaml
  controllers/provider-aws/cmd/gardener-extension-validator-aws/app/app.go
  controllers/provider-aws/cmd/gardener-extension-validator-aws/app/options.go
  controllers/provider-aws/cmd/gardener-extension-validator-aws/main.go
  controllers/provider-aws/example/40-validatingwebhookconfiguration.yaml
  controllers/provider-aws/example/validator-aws-certs/tls.crt
  controllers/provider-aws/example/validator-aws-certs/tls.key
  controllers/provider-aws/pkg/apis/aws/validation/infrastructure.go
  controllers/provider-aws/pkg/apis/aws/validation/infrastructure_test.go
  controllers/provider-aws/pkg/apis/aws/validation/shoot.go
  controllers/provider-aws/pkg/apis/aws/validation/shoot_test.go
  controllers/provider-aws/pkg/apis/aws/validation/worker.go
  controllers/provider-aws/pkg/validator/serialization.go
  controllers/provider-aws/pkg/validator/shoot_handler.go
  controllers/provider-aws/pkg/validator/shoot_validator.go
  pkg/controller/cmd/options.go
  pkg/util/serialization.go
Labels: needs/ok-to-test

#470 [release-1.0] Fix image vector overwrite for shoot-dns-service
  controllers/extension-shoot-dns-service/charts/extension-shoot-dns-service/templates/deployment.yaml
  controllers/extension-shoot-dns-service/example/controller-registration.yaml
Labels: kind/bug, needs/ok-to-test

#469 Fix image vector overwrite for shoot-dns-service
  controllers/extension-shoot-dns-service/charts/extension-shoot-dns-service/templates/deployment.yaml
  controllers/extension-shoot-dns-service/example/controller-registration.yaml
Labels: kind/bug, needs/ok-to-test

#468 Vendor gardener/gardener@7672763b3716
  go.mod
  go.sum
  pkg/mock/gardener/client/kubernetes/mocks.go
  vendor/github.com/gardener/gardener/pkg/api/extensions/accessor.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/garden/v1beta1/types.go
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/client.go
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/clientset.go
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/types.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/clientset.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/doc.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/scheme/doc.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/scheme/register.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/typed/machine/v1alpha1/alicloudmachineclass.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/typed/machine/v1alpha1/awsmachineclass.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/typed/machine/v1alpha1/azuremachineclass.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/typed/machine/v1alpha1/doc.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/typed/machine/v1alpha1/gcpmachineclass.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/typed/machine/v1alpha1/generated_expansion.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/typed/machine/v1alpha1/machine.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/typed/machine/v1alpha1/machine_client.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/typed/machine/v1alpha1/machinedeployment.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/typed/machine/v1alpha1/machineset.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/typed/machine/v1alpha1/machinetemplate.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/typed/machine/v1alpha1/openstackmachineclass.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/typed/machine/v1alpha1/packetmachineclass.go
  vendor/github.com/gardener/gardener/pkg/client/machine/clientset/versioned/typed/machine/v1alpha1/scale.go
  vendor/github.com/gardener/gardener/pkg/operation/common/types.go
  vendor/github.com/gardener/gardener/pkg/scheduler/controller/shoot/scheduler_control.go
  vendor/github.com/gardener/gardener/pkg/scheduler/utils/networks.go
  vendor/github.com/gardener/gardener/pkg/utils/errors/errors.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/client/client.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/kubernetes.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/patch.go
  vendor/github.com/gardener/gardener/test/integration/framework/common.go
  vendor/github.com/gardener/gardener/test/integration/framework/garden_operation.go
  vendor/github.com/gardener/gardener/test/integration/framework/shoot_operations.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/zz_generated.deepcopy.go
  vendor/github.com/gardener/machine-controller-manager/pkg/client/clientset/versioned/scheme/register.go
  vendor/modules.txt
Labels: needs/ok-to-test

#471 Update provider-gcp README.md
  controllers/provider-alicloud/docs/usage-as-operator.md
  controllers/provider-gcp/README.md
Labels: needs/ok-to-test

#464 Add bucket lifecycle rule for incomplete multipart uploads
  controllers/provider-alicloud/pkg/alicloud/client/client.go
  controllers/provider-aws/pkg/aws/client/client.go
Labels: needs/ok-to-test

#473 Prefix tags with 'v'
  VERSION
  controllers/extension-certificate-service/example/controller-registration.yaml
  controllers/extension-shoot-cert-service/example/controller-registration.yaml
  controllers/extension-shoot-dns-service/example/controller-registration.yaml
  controllers/networking-calico/example/controller-registration.yaml
  controllers/os-coreos-alicloud/example/controller-registration.yaml
  controllers/os-coreos/example/controller-registration.yaml
  controllers/os-suse-jeos/example/controller-registration.yaml
  controllers/os-ubuntu-alicloud/example/controller-registration.yaml
  controllers/os-ubuntu/example/controller-registration.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-packet/example/controller-registration.yaml
Labels: needs/ok-to-test
