Repository gardener/gardener-extensions, pull requests merged in 2019-04, with the labels that each got.

#41 Make CI-pipeline generate controller registrations for next dev cycle
  .ci/pipeline_definitions
  hack/generate-controller-registration.sh
Labels: area/delivery, kind/enhancement, needs/lgtm, needs/review, priority/normal, size/xs

#42 Enhance output of `clean` and `generate` in check
  hack/check-generate.sh
  hack/clean.sh
Labels: area/quality, component/gardener, exp/beginner, kind/enhancement, needs/lgtm, needs/ok-to-test, needs/review, priority/normal, size/s, status/in-progress

#46 Several improvements to the infrastructure controllers
  controllers/provider-alicloud/example/crd-cluster.yaml
  controllers/provider-aws/example/Infrastructure.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-aws/example/controlplane.yaml
  controllers/provider-aws/example/crd-cluster.yaml
  controllers/provider-aws/pkg/controller/infrastructure/actuator_reconcile.go
  controllers/provider-azure/example/crd-cluster.yaml
  controllers/provider-gcp/example/Infrastructure.yaml
  controllers/provider-gcp/example/crd-cluster.yaml
  controllers/provider-gcp/pkg/controller/infrastructure/actuator.go
  controllers/provider-local/example/controlplane.yaml
  controllers/provider-local/example/crd-cluster.yaml
  controllers/provider-openstack/example/crd-cluster.yaml
  pkg/controller/cluster.go
  pkg/controller/controlplane/mapper.go
  pkg/controller/infrastructure/actuator.go
  pkg/controller/infrastructure/controller.go
  pkg/controller/infrastructure/predicate.go
  pkg/controller/infrastructure/reconciler.go
Labels: area/usability, exp/expert, kind/enhancement, needs/review, priority/normal, size/m, status/in-progress, status/under-investigation

#43 Add Azure infrastructure provider
  controllers/hyper/cmd/gardener-extension-hyper/app/app.go
  controllers/os-suse-jeos/example/controller-registration.yaml
  controllers/provider-azure/charts/internal/azure-infra/Chart.yaml
  controllers/provider-azure/charts/internal/azure-infra/templates/main.tf
  controllers/provider-azure/charts/internal/azure-infra/templates/terraform.tfvars
  controllers/provider-azure/charts/internal/azure-infra/templates/variables.tf
  controllers/provider-azure/charts/internal/azure-infra/values.yaml
  controllers/provider-azure/cmd/gardener-extension-provider-azure/app/app.go
  controllers/provider-azure/example/infrastructure.yaml
  controllers/provider-azure/hack/generate-code
  controllers/provider-azure/pkg/apis/azure/doc.go
  controllers/provider-azure/pkg/apis/azure/install/install.go
  controllers/provider-azure/pkg/apis/azure/register.go
  controllers/provider-azure/pkg/apis/azure/types_infrastructure.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/defaults.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/doc.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/register.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/types_infrastructure.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/zz_generated.conversion.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-azure/pkg/apis/azure/v1alpha1/zz_generated.defaults.go
  controllers/provider-azure/pkg/apis/azure/zz_generated.deepcopy.go
  controllers/provider-azure/pkg/controller/controller.go
  controllers/provider-azure/pkg/controller/infrastructure/actuator.go
  controllers/provider-azure/pkg/controller/infrastructure/actuator_delete.go
  controllers/provider-azure/pkg/controller/infrastructure/actuator_reconcile.go
  controllers/provider-azure/pkg/controller/infrastructure/add.go
  controllers/provider-azure/pkg/internal/auth.go
  controllers/provider-azure/pkg/internal/auth_test.go
  controllers/provider-azure/pkg/internal/imagevector/imagevector.go
  controllers/provider-azure/pkg/internal/infrastructure/infrastructure.go
  controllers/provider-azure/pkg/internal/infrastructure/terraform.go
  controllers/provider-azure/pkg/internal/infrastructure/terraform_test.go
  controllers/provider-azure/pkg/internal/internal_test.go
  controllers/provider-azure/pkg/internal/scheme.go
  controllers/provider-azure/pkg/internal/terraform.go
  controllers/provider-azure/pkg/internal/terraform_test.go
  controllers/provider-gcp/pkg/internal/imagevector/imagevector.go
Labels: area/open-source, exp/intermediate, kind/enhancement, platform/az, priority/normal, reviewed/lgtm, size/xl, status/accepted, topology/seed

#51 Improve generate script and local dev experience
  hack/generate-controller-registration.sh
  hack/install-requirements.sh
Labels: area/documentation, area/open-source, kind/enhancement, needs/lgtm, priority/normal, size/xs

#49 Delete remnant route entries
  controllers/provider-gcp/pkg/controller/infrastructure/actuator_delete.go
  controllers/provider-gcp/pkg/internal/client/client.go
  controllers/provider-gcp/pkg/internal/client/types.go
  controllers/provider-gcp/pkg/internal/infrastructure/infrastructure.go
  controllers/provider-gcp/pkg/internal/infrastructure/infrastructure_test.go
  controllers/provider-gcp/pkg/internal/mock/client/doc.go
  controllers/provider-gcp/pkg/internal/mock/client/mocks.go
Labels: area/robustness, exp/intermediate, kind/enhancement, platform/gcp, priority/normal, reviewed/lgtm, size/s, status/accepted, topology/seed

#48 Add controlplane webhooks
  Gopkg.lock
  Makefile
  controllers/provider-aws/charts/provider-aws/templates/deployment.yaml
  controllers/provider-aws/charts/provider-aws/templates/rbac.yaml
  controllers/provider-aws/cmd/gardener-extension-provider-aws/app/app.go
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-aws/pkg/webhook/controlplane/add.go
  controllers/provider-aws/pkg/webhook/controlplane/mutator.go
  controllers/provider-aws/pkg/webhook/controlplaneexposure/add.go
  controllers/provider-aws/pkg/webhook/controlplaneexposure/mutator.go
  controllers/provider-aws/pkg/webhook/webhook.go
  pkg/webhook/cmd/options.go
  pkg/webhook/controlplane/controlplane.go
  pkg/webhook/controlplane/handler.go
  pkg/webhook/controlplane/mutator.go
  pkg/webhook/utils.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/builder/builder.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/builder/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/bootstrap.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/certgenerator.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/selfsigned.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/util.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/provisioner.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/atomic/atomic_writer.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/certwriter.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/error.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/fs.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/secret.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/util.go
Labels: area/control-plane, exp/expert, kind/enhancement, priority/normal, reviewed/lgtm, size/xl, status/accepted

#52 Implement AWS controlplane webhooks
  controllers/provider-aws/pkg/aws/types.go
  controllers/provider-aws/pkg/controller/controlplane/actuator.go
  controllers/provider-aws/pkg/webhook/controlplane/mutator.go
  controllers/provider-aws/pkg/webhook/controlplaneexposure/mutator.go
  pkg/webhook/controlplane/utils.go
Labels: area/control-plane, exp/intermediate, kind/enhancement, platform/aws, priority/normal, reviewed/lgtm, size/m, status/accepted, topology/seed

#61 Fix install-requirements.sh MacOs warning
  hack/install-requirements.sh
Labels: needs/ok-to-test

#53 Add AWS controlplane webhooks tests
  controllers/provider-aws/pkg/webhook/controlplane/mutator.go
  controllers/provider-aws/pkg/webhook/controlplane/mutator_test.go
  controllers/provider-aws/pkg/webhook/controlplaneexposure/mutator.go
  controllers/provider-aws/pkg/webhook/controlplaneexposure/mutator_test.go
  pkg/webhook/controlplane/test/matchers.go
  pkg/webhook/controlplane/utils.go
Labels: needs/ok-to-test, reviewed/lgtm

#58 Constrain route names
  controllers/provider-gcp/pkg/controller/infrastructure/actuator_delete.go
  controllers/provider-gcp/pkg/internal/infrastructure/infrastructure.go
  controllers/provider-gcp/pkg/internal/infrastructure/infrastructure_test.go
Labels: needs/ok-to-test

#45 Added OpenStack Provider
  controllers/provider-openstack/charts/internal/openstack-infra/Chart.yaml
  controllers/provider-openstack/charts/internal/openstack-infra/templates/_helpers.tpl
  controllers/provider-openstack/charts/internal/openstack-infra/templates/main.tf
  controllers/provider-openstack/charts/internal/openstack-infra/templates/terraform.tfvars
  controllers/provider-openstack/charts/internal/openstack-infra/templates/variables.tf
  controllers/provider-openstack/charts/internal/openstack-infra/values.yaml
  controllers/provider-openstack/charts/provider-openstack/templates/rbac.yaml
  controllers/provider-openstack/cmd/gardener-extension-provider-openstack/app/app.go
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-openstack/example/infrastructure.yaml
  controllers/provider-openstack/hack/generate-code
  controllers/provider-openstack/pkg/apis/openstack/doc.go
  controllers/provider-openstack/pkg/apis/openstack/install/install.go
  controllers/provider-openstack/pkg/apis/openstack/register.go
  controllers/provider-openstack/pkg/apis/openstack/types_infrastructure.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/defaults.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/doc.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/register.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/types_infrastructure.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/zz_generated.conversion.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/zz_generated.defaults.go
  controllers/provider-openstack/pkg/apis/openstack/zz_generated.deepcopy.go
  controllers/provider-openstack/pkg/controller/controller.go
  controllers/provider-openstack/pkg/controller/infrastructure/actuator.go
  controllers/provider-openstack/pkg/controller/infrastructure/actuator_delete.go
  controllers/provider-openstack/pkg/controller/infrastructure/actuator_reconcile.go
  controllers/provider-openstack/pkg/controller/infrastructure/add.go
  controllers/provider-openstack/pkg/imagevector/imagevector.go
  controllers/provider-openstack/pkg/internal/credentials.go
  controllers/provider-openstack/pkg/internal/infrastructure/infrastructure.go
  controllers/provider-openstack/pkg/internal/infrastructure/terraform.go
  controllers/provider-openstack/pkg/internal/infrastructure/terraform_test.go
  controllers/provider-openstack/pkg/internal/internal_test.go
  controllers/provider-openstack/pkg/internal/scheme.go
  controllers/provider-openstack/pkg/internal/terraform.go
  controllers/provider-openstack/pkg/internal/terraform_test.go
  controllers/provider-openstack/pkg/openstack/types.go
Labels: area/open-source, exp/intermediate, kind/enhancement, needs/ok-to-test, platform/openstack, priority/normal, size/xl, topology/seed

#59 Add controlplane webhooks tests
  pkg/controller/cmd/options_test.go
  pkg/mock/apimachinery/api/meta/doc.go
  pkg/mock/apimachinery/api/meta/mocks.go
  pkg/mock/controller-runtime/webhook/admission/doc.go
  pkg/mock/controller-runtime/webhook/admission/mocks.go
  pkg/mock/controller-runtime/webhook/admission/types/doc.go
  pkg/mock/controller-runtime/webhook/admission/types/mocks.go
  pkg/mock/gardener-extensions/webhook/controlplane/doc.go
  pkg/mock/gardener-extensions/webhook/controlplane/mocks.go
  pkg/util/test/options.go
  pkg/webhook/cmd/options_test.go
  pkg/webhook/controlplane/handler.go
  pkg/webhook/controlplane/handler_test.go
  pkg/webhook/utils_test.go
Labels: needs/ok-to-test

#62 Remove local provider
  Dockerfile
  Makefile
  controllers/hyper/cmd/gardener-extension-hyper/app/app.go
  controllers/provider-local/README.md
  controllers/provider-local/charts/images.yaml
  controllers/provider-local/charts/provider-local/Chart.yaml
  controllers/provider-local/charts/provider-local/doc.go
  controllers/provider-local/charts/provider-local/templates/deployment.yaml
  controllers/provider-local/charts/provider-local/templates/rbac.yaml
  controllers/provider-local/charts/provider-local/templates/serviceaccount.yaml
  controllers/provider-local/charts/provider-local/values.yaml
  controllers/provider-local/cmd/gardener-extension-provider-local/app/app.go
  controllers/provider-local/cmd/gardener-extension-provider-local/main.go
  controllers/provider-local/example/controller-registration.yaml
  controllers/provider-local/example/controlplane.yaml
  controllers/provider-local/example/crd-cluster.yaml
  controllers/provider-local/example/crd-controlplane.yaml
  controllers/provider-local/example/crd-infrastructure.yaml
  controllers/provider-local/pkg/controlplane/actuator.go
  controllers/provider-local/pkg/controlplane/add.go
  controllers/provider-local/pkg/imagevector/imagevector.go
  controllers/provider-local/pkg/local/predicate.go
  controllers/provider-local/pkg/local/types.go
  extensions.yaml
Labels: needs/ok-to-test

#65 Fix comparison of networks during route deletion
  controllers/provider-gcp/pkg/internal/infrastructure/infrastructure.go
Labels: needs/ok-to-test

#63 Add kubelet config to AWS controlplane webhook
  Gopkg.lock
  Gopkg.toml
  controllers/provider-aws/pkg/webhook/controlplane/add.go
  controllers/provider-aws/pkg/webhook/controlplane/mutator.go
  controllers/provider-aws/pkg/webhook/controlplane/mutator_test.go
  pkg/util/pointers.go
  pkg/webhook/controlplane/filecontentinlinecodec.go
  pkg/webhook/controlplane/filecontentinlinecodec_test.go
  pkg/webhook/controlplane/handler_test.go
  pkg/webhook/controlplane/kubeletconfigcodec.go
  pkg/webhook/controlplane/kubeletconfigcodec_test.go
  pkg/webhook/controlplane/unitserializer.go
  pkg/webhook/controlplane/unitserializer_test.go
  pkg/webhook/controlplane/utils.go
  vendor/github.com/coreos/go-systemd/LICENSE
  vendor/github.com/coreos/go-systemd/NOTICE
  vendor/github.com/coreos/go-systemd/unit/deserialize.go
  vendor/github.com/coreos/go-systemd/unit/escape.go
  vendor/github.com/coreos/go-systemd/unit/option.go
  vendor/github.com/coreos/go-systemd/unit/serialize.go
  vendor/k8s.io/kubelet/LICENSE
  vendor/k8s.io/kubelet/config/v1beta1/doc.go
  vendor/k8s.io/kubelet/config/v1beta1/register.go
  vendor/k8s.io/kubelet/config/v1beta1/types.go
  vendor/k8s.io/kubelet/config/v1beta1/zz_generated.deepcopy.go
Labels: needs/ok-to-test

#68 [ci:component:github.com/gardener/terraformer:0.11.0->0.12.0]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
Labels: needs/ok-to-test
