Repository gardener/gardener-extensions, pull requests merged in 2020-02, with the labels that each got.

#591 Remove `install` command from Makefile
  Makefile
Labels: needs/ok-to-test, reviewed/ok-to-test

#592 Add list of known extension implementations
  README.md
Labels: needs/ok-to-test

#594 Update set_dependency_version for external-dns-management
  hack/.ci/set_dependency_version
Labels: needs/ok-to-test

#595 Unify log keys to be lowercase
  pkg/controller/healthcheck/controller.go
  pkg/controller/healthcheck/reconciler.go
Labels: needs/ok-to-test

#596 Generate v1beta1 version of ControllerRegistrations
  hack/generate-controller-registration.sh
Labels: needs/ok-to-test

#598 Remove hack/code-generator/tools.go
  hack/code-generator/tools.go
Labels: needs/ok-to-test

#599 Vendor gardener/gardener@v1.0.1
  README.md
  go.mod
  go.sum
  pkg/controller/healthcheck/general/daemonset.go
  pkg/controller/healthcheck/general/statefulsets.go
  pkg/controller/worker/genericactuator/actuator.go
  pkg/controller/worker/machines_test.go
  test/e2e/framework/networkpolicies/generators/networkpolicies.go
  test/integration/healthcheck/healthcheck_operation.go
  test/integration/operation/shoot_operation.go
  vendor/github.com/gardener/gardener/pkg/api/extensions/accessor.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_backupbucket.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_backupbucket.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_backupbucket.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_backupentry.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_controlplane.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_extension.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_infrastructure.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_network.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_worker.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/controllerutils/miscellaneous.go
  vendor/github.com/gardener/gardener/pkg/operation/common/types.go
  vendor/github.com/gardener/gardener/pkg/operation/common/utils.go
  vendor/github.com/gardener/gardener/pkg/scheduler/controller/shoot/scheduler_control.go
  vendor/modules.txt
Labels: needs/ok-to-test

#601 Support IP address as --webhook-config-url
  pkg/webhook/certificates.go
Labels: needs/ok-to-test

#602 Use in-cluster shoot API-server urls for health-checks
  go.mod
  go.sum
  pkg/util/shoot_clients.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_worker.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: needs/ok-to-test

#605 Remove .spec.activeDeadlineSeconds from the terraformer Pod
  go.sum
  pkg/mock/gardener-extensions/terraformer/mocks.go
  pkg/terraformer/config.go
  pkg/terraformer/terraformer.go
  pkg/terraformer/types.go
Labels: kind/bug, needs/ok-to-test
