Repository gardener/gardener-extensions, pull requests merged in 2020-01, with the labels that each got.

#526 Add documentation for the networking-calico extension
  controllers/networking-calico/README.md
Labels: needs/ok-to-test

#482 Allow region-ized fields in OpenStack CloudProfileConfig
  controllers/provider-azure/pkg/internal/scheme.go
  controllers/provider-openstack/docs/usage-as-operator.md
  controllers/provider-openstack/hack/api-reference/api.md
  controllers/provider-openstack/pkg/apis/openstack/helper/helper.go
  controllers/provider-openstack/pkg/apis/openstack/helper/helper_test.go
  controllers/provider-openstack/pkg/apis/openstack/types_cloudprofile.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/types_cloudprofile.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/zz_generated.conversion.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-openstack/pkg/apis/openstack/validation/cloudprofile.go
  controllers/provider-openstack/pkg/apis/openstack/validation/cloudprofile_test.go
  controllers/provider-openstack/pkg/apis/openstack/validation/controlplane.go
  controllers/provider-openstack/pkg/apis/openstack/validation/controlplane_test.go
  controllers/provider-openstack/pkg/apis/openstack/validation/infrastructure.go
  controllers/provider-openstack/pkg/apis/openstack/validation/infrastructure_test.go
  controllers/provider-openstack/pkg/apis/openstack/zz_generated.deepcopy.go
  controllers/provider-openstack/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-openstack/pkg/controller/controlplane/valuesprovider_test.go
  controllers/provider-openstack/pkg/controller/infrastructure/actuator.go
  controllers/provider-openstack/pkg/controller/worker/machines.go
  controllers/provider-openstack/pkg/controller/worker/machines_test.go
  controllers/provider-openstack/pkg/internal/infrastructure/terraform.go
  controllers/provider-openstack/pkg/internal/infrastructure/terraform_test.go
  controllers/provider-openstack/pkg/internal/scheme.go
Labels: needs/ok-to-test

#521 Consistent naming for worker CIDRs
  controllers/provider-alicloud/charts/internal/alicloud-infra/templates/main.tf
  controllers/provider-alicloud/charts/internal/alicloud-infra/values.yaml
  controllers/provider-alicloud/docs/usage-as-end-user.md
  controllers/provider-alicloud/example/30-infrastructure.yaml
  controllers/provider-alicloud/hack/api-reference/api.md
  controllers/provider-alicloud/pkg/apis/alicloud/types_infrastructure.go
  controllers/provider-alicloud/pkg/apis/alicloud/v1alpha1/types_infrastructure.go
  controllers/provider-alicloud/pkg/apis/alicloud/v1alpha1/zz_generated.conversion.go
  controllers/provider-alicloud/pkg/apis/alicloud/validation/infrastructure.go
  controllers/provider-alicloud/pkg/apis/alicloud/validation/infrastructure_test.go
  controllers/provider-alicloud/pkg/controller/infrastructure/terraform.go
  controllers/provider-alicloud/pkg/controller/infrastructure/terraform_test.go
  controllers/provider-alicloud/test/tm/generator.go
  controllers/provider-gcp/charts/internal/gcp-infra/templates/main.tf
  controllers/provider-gcp/charts/internal/gcp-infra/values.yaml
  controllers/provider-gcp/docs/usage-as-end-user.md
  controllers/provider-gcp/example/30-infrastructure.yaml
  controllers/provider-gcp/hack/api-reference/api.md
  controllers/provider-gcp/pkg/apis/gcp/types_infrastructure.go
  controllers/provider-gcp/pkg/apis/gcp/v1alpha1/types_infrastructure.go
  controllers/provider-gcp/pkg/apis/gcp/v1alpha1/zz_generated.conversion.go
  controllers/provider-gcp/pkg/apis/gcp/validation/infrastructure.go
  controllers/provider-gcp/pkg/apis/gcp/validation/infrastructure_test.go
  controllers/provider-gcp/pkg/internal/infrastructure/terraform.go
  controllers/provider-gcp/pkg/internal/infrastructure/terraform_test.go
  controllers/provider-gcp/test/tm/generator.go
  controllers/provider-openstack/charts/internal/openstack-infra/templates/main.tf
  controllers/provider-openstack/charts/internal/openstack-infra/values.yaml
  controllers/provider-openstack/docs/usage-as-end-user.md
  controllers/provider-openstack/example/30-infrastructure.yaml
  controllers/provider-openstack/hack/api-reference/api.md
  controllers/provider-openstack/pkg/apis/openstack/types_infrastructure.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/types_infrastructure.go
  controllers/provider-openstack/pkg/apis/openstack/v1alpha1/zz_generated.conversion.go
  controllers/provider-openstack/pkg/apis/openstack/validation/infrastructure.go
  controllers/provider-openstack/pkg/apis/openstack/validation/infrastructure_test.go
  controllers/provider-openstack/pkg/internal/infrastructure/terraform.go
  controllers/provider-openstack/pkg/internal/infrastructure/terraform_test.go
  controllers/provider-openstack/test/tm/generator.go
  go.sum
Labels: needs/ok-to-test

#519 Support for Kubernetes v1.17
  controllers/provider-alicloud/README.md
  controllers/provider-aws/README.md
  controllers/provider-aws/charts/images.yaml
  controllers/provider-aws/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml
  controllers/provider-aws/charts/internal/cloud-controller-manager/values.yaml
  controllers/provider-aws/pkg/aws/types.go
  controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-aws/pkg/webhook/controlplane/ensurer.go
  controllers/provider-aws/pkg/webhook/controlplane/ensurer_test.go
  controllers/provider-azure/README.md
  controllers/provider-azure/charts/images.yaml
  controllers/provider-azure/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml
  controllers/provider-azure/charts/internal/cloud-controller-manager/values.yaml
  controllers/provider-azure/pkg/azure/types.go
  controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-azure/pkg/webhook/controlplane/ensurer.go
  controllers/provider-azure/pkg/webhook/controlplane/ensurer_test.go
  controllers/provider-gcp/README.md
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-gcp/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml
  controllers/provider-gcp/charts/internal/cloud-controller-manager/values.yaml
  controllers/provider-gcp/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-gcp/pkg/gcp/types.go
  controllers/provider-gcp/pkg/webhook/controlplane/ensurer.go
  controllers/provider-gcp/pkg/webhook/controlplane/ensurer_test.go
  controllers/provider-openstack/README.md
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-openstack/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml
  controllers/provider-openstack/pkg/openstack/types.go
  controllers/provider-openstack/pkg/webhook/controlplane/ensurer.go
  controllers/provider-openstack/pkg/webhook/controlplane/ensurer_test.go
  controllers/provider-packet/README.md
  go.sum
Labels: needs/ok-to-test

#533 Allow Azure cloud-controller to create service events
  controllers/provider-azure/charts/internal/cloud-controller-manager-shoot/templates/rbac-cloud-controller.yaml
Labels: needs/ok-to-test, platform/az

#534 Revert golangci/golangci-lint to v1.18.0
  hack/check.sh
  hack/install-requirements.sh
Labels: needs/ok-to-test, reviewed/ok-to-test

#532 Azure-CCM: Bundle cloudProviderRateLimitQPS[Write] to the maxNodes
  controllers/provider-azure/charts/internal/cloud-provider-config/templates/cloud-provider-config.tpl
  controllers/provider-azure/charts/internal/cloud-provider-config/values.yaml
  controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-azure/pkg/controller/controlplane/valuesprovider_test.go
Labels: needs/ok-to-test, platform/az

#529 Handle hibernated cluster w/ missing API service
  controllers/provider-alicloud/pkg/webhook/controlplaneexposure/ensurer.go
  controllers/provider-alicloud/pkg/webhook/controlplaneexposure/ensurer_test.go
  controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-azure/pkg/webhook/controlplaneexposure/ensurer.go
  controllers/provider-azure/pkg/webhook/controlplaneexposure/ensurer_test.go
  controllers/provider-gcp/pkg/webhook/controlplaneexposure/ensurer.go
  controllers/provider-gcp/pkg/webhook/controlplaneexposure/ensurer_test.go
  controllers/provider-openstack/pkg/webhook/controlplaneexposure/ensurer.go
  controllers/provider-openstack/pkg/webhook/controlplaneexposure/ensurer_test.go
Labels: needs/ok-to-test

#520 Allow to disable AWS ECR access via infrastructure config
  controllers/provider-aws/charts/internal/aws-infra/templates/main.tf
  controllers/provider-aws/charts/internal/aws-infra/values.yaml
  controllers/provider-aws/docs/usage-as-end-user.md
  controllers/provider-aws/example/30-infrastructure.yaml
  controllers/provider-aws/hack/api-reference/api.md
  controllers/provider-aws/pkg/apis/aws/types_infrastructure.go
  controllers/provider-aws/pkg/apis/aws/v1alpha1/types_infrastructure.go
  controllers/provider-aws/pkg/apis/aws/v1alpha1/zz_generated.conversion.go
  controllers/provider-aws/pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-aws/pkg/apis/aws/zz_generated.deepcopy.go
  controllers/provider-aws/pkg/controller/infrastructure/actuator_reconcile.go
Labels: needs/ok-to-test

#540 Clean up ControllerConfigurations from machine images
  controllers/provider-alicloud/charts/provider-alicloud/templates/configmap.yaml
  controllers/provider-alicloud/charts/provider-alicloud/values.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-alicloud/pkg/apis/alicloud/helper/helper_test.go
  controllers/provider-alicloud/pkg/controller/worker/machines_test.go
  controllers/provider-aws/charts/provider-aws/templates/configmap.yaml
  controllers/provider-aws/charts/provider-aws/values.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-aws/pkg/apis/aws/helper/helper_test.go
  controllers/provider-aws/pkg/controller/worker/machines_test.go
  controllers/provider-azure/charts/provider-azure/templates/configmap.yaml
  controllers/provider-azure/charts/provider-azure/values.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-gcp/charts/provider-gcp/templates/configmap.yaml
  controllers/provider-gcp/charts/provider-gcp/values.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-openstack/charts/provider-openstack/templates/configmap.yaml
  controllers/provider-openstack/charts/provider-openstack/values.yaml
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-openstack/pkg/controller/worker/machines_test.go
  controllers/provider-packet/charts/provider-packet/templates/configmap.yaml
  controllers/provider-packet/charts/provider-packet/values.yaml
  controllers/provider-packet/example/controller-registration.yaml
  controllers/provider-packet/pkg/controller/worker/machines_test.go
  hack/check.sh
Labels: needs/ok-to-test

#541 Fix networking-calico installation
  controllers/networking-calico/charts/networking-calico/templates/configmap.yaml
  controllers/networking-calico/charts/networking-calico/templates/deployment.yaml
  controllers/networking-calico/charts/networking-calico/values.yaml
  controllers/networking-calico/example/controller-registration.yaml
Labels: kind/bug, needs/ok-to-test

#509 Add hack script for extensions and webhook local developement
  Makefile
  controllers/provider-alicloud/charts/provider-alicloud/templates/deployment.yaml
  controllers/provider-alicloud/charts/provider-alicloud/templates/service.yaml
  controllers/provider-alicloud/charts/provider-alicloud/values.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-aws/charts/provider-aws/templates/deployment.yaml
  controllers/provider-aws/charts/provider-aws/templates/service.yaml
  controllers/provider-aws/charts/provider-aws/values.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-azure/charts/provider-azure/templates/deployment.yaml
  controllers/provider-azure/charts/provider-azure/templates/service.yaml
  controllers/provider-azure/charts/provider-azure/values.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-gcp/charts/provider-gcp/templates/deployment.yaml
  controllers/provider-gcp/charts/provider-gcp/templates/service.yaml
  controllers/provider-gcp/charts/provider-gcp/values.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-openstack/charts/provider-openstack/templates/deployment.yaml
  controllers/provider-openstack/charts/provider-openstack/templates/service.yaml
  controllers/provider-openstack/charts/provider-openstack/values.yaml
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-packet/charts/provider-packet/templates/deployment.yaml
  controllers/provider-packet/charts/provider-packet/templates/service.yaml
  controllers/provider-packet/charts/provider-packet/values.yaml
  controllers/provider-packet/example/controller-registration.yaml
  hack/hook-me.sh
Labels: needs/ok-to-test, reviewed/ok-to-test

#542 Fix issue in cp ctrl that sometimes preserved last error
  pkg/controller/controlplane/reconciler.go
Labels: needs/ok-to-test

#544 add region mapping to cloudprofile for alicloud
  controllers/provider-alicloud/example/30-infrastructure.yaml
  controllers/provider-alicloud/example/30-worker.yaml
  controllers/provider-alicloud/hack/api-reference/api.md
  controllers/provider-alicloud/pkg/apis/alicloud/helper/helper.go
  controllers/provider-alicloud/pkg/apis/alicloud/helper/helper_test.go
  controllers/provider-alicloud/pkg/apis/alicloud/types_cloudprofile.go
  controllers/provider-alicloud/pkg/apis/alicloud/v1alpha1/types_cloudprofile.go
  controllers/provider-alicloud/pkg/apis/alicloud/v1alpha1/zz_generated.conversion.go
  controllers/provider-alicloud/pkg/apis/alicloud/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-alicloud/pkg/apis/alicloud/validation/cloudprofile.go
  controllers/provider-alicloud/pkg/apis/alicloud/validation/cloudprofile_test.go
  controllers/provider-alicloud/pkg/apis/alicloud/zz_generated.deepcopy.go
  controllers/provider-alicloud/pkg/controller/infrastructure/actuator.go
  controllers/provider-alicloud/pkg/controller/worker/machine_images.go
  controllers/provider-alicloud/pkg/controller/worker/machines.go
  controllers/provider-alicloud/pkg/controller/worker/machines_test.go
  controllers/provider-aws/pkg/apis/aws/helper/helper_test.go
Labels: needs/ok-to-test

#546 fixing healthcheck wrong shoot client injection
  pkg/controller/healthcheck/actuator.go
  pkg/controller/healthcheck/general/daemonset.go
  pkg/controller/healthcheck/general/deployment.go
  pkg/controller/healthcheck/general/managed_resource.go
  pkg/controller/healthcheck/general/statefulsets.go
  pkg/controller/healthcheck/healtcheck_actuator.go
  pkg/controller/healthcheck/reconciler.go
  pkg/controller/healthcheck/worker/sufficient_nodes.go
Labels: needs/ok-to-test

#548 Use machineclass constant from generic worker actuator
  controllers/provider-alicloud/charts/internal/machineclass/templates/machineclass.yaml
  controllers/provider-alicloud/charts/internal/machineclass/values.yaml
  controllers/provider-alicloud/pkg/controller/worker/machines.go
  controllers/provider-alicloud/pkg/controller/worker/machines_test.go
  controllers/provider-aws/charts/internal/machineclass/templates/machineclass.yaml
  controllers/provider-aws/charts/internal/machineclass/values.yaml
  controllers/provider-aws/pkg/controller/worker/machines.go
  controllers/provider-aws/pkg/controller/worker/machines_test.go
  controllers/provider-azure/charts/internal/machineclass/templates/machineclass.yaml
  controllers/provider-azure/charts/internal/machineclass/values.yaml
  controllers/provider-azure/pkg/controller/worker/machines.go
  controllers/provider-azure/pkg/controller/worker/machines_test.go
  controllers/provider-gcp/charts/internal/machineclass/templates/machineclass.yaml
  controllers/provider-gcp/charts/internal/machineclass/values.yaml
  controllers/provider-gcp/pkg/controller/worker/machines.go
  controllers/provider-gcp/pkg/controller/worker/machines_test.go
  controllers/provider-openstack/charts/internal/machineclass/templates/machineclass.yaml
  controllers/provider-openstack/charts/internal/machineclass/values.yaml
  controllers/provider-openstack/pkg/controller/worker/machines.go
  controllers/provider-openstack/pkg/controller/worker/machines_test.go
  controllers/provider-packet/charts/internal/machineclass/templates/machineclass.yaml
  controllers/provider-packet/charts/internal/machineclass/values.yaml
  controllers/provider-packet/pkg/controller/worker/machines.go
  controllers/provider-packet/pkg/controller/worker/machines_test.go
  pkg/controller/worker/genericactuator/actuator.go
Labels: needs/ok-to-test

#551 Fix networking-calico local dev
  Makefile
Labels: needs/ok-to-test

#549 Move VPA config in charts to proper place
  controllers/provider-alicloud/charts/provider-alicloud/templates/vpa.yaml
  controllers/provider-alicloud/charts/provider-alicloud/values.yaml
  controllers/provider-alicloud/example/controller-registration.yaml
  controllers/provider-aws/charts/provider-aws/templates/vpa.yaml
  controllers/provider-aws/charts/provider-aws/values.yaml
  controllers/provider-aws/example/controller-registration.yaml
  controllers/provider-azure/charts/provider-azure/templates/vpa.yaml
  controllers/provider-azure/charts/provider-azure/values.yaml
  controllers/provider-azure/example/controller-registration.yaml
  controllers/provider-gcp/charts/provider-gcp/templates/vpa.yaml
  controllers/provider-gcp/charts/provider-gcp/values.yaml
  controllers/provider-gcp/example/controller-registration.yaml
  controllers/provider-openstack/charts/provider-openstack/templates/vpa.yaml
  controllers/provider-openstack/charts/provider-openstack/values.yaml
  controllers/provider-openstack/example/controller-registration.yaml
  controllers/provider-packet/charts/provider-packet/templates/vpa.yaml
  controllers/provider-packet/charts/provider-packet/values.yaml
  controllers/provider-packet/example/controller-registration.yaml
Labels: needs/ok-to-test

#550 Calico extension defines logging config
  controllers/networking-calico/charts/networking-calico/templates/configmap-logging.yaml
  controllers/networking-calico/example/controller-registration.yaml
Labels: needs/ok-to-test

#552 Use instead of until old API group is removed
  controllers/provider-alicloud/test/tm/generator.go
  controllers/provider-gcp/test/tm/generator.go
  controllers/provider-openstack/test/tm/generator.go
Labels: needs/ok-to-test

#553 Rename introduced labels to resourceLabels as labels is already taken
  controllers/provider-gcp/charts/internal/machineclass/templates/machineclass.yaml
  controllers/provider-gcp/charts/internal/machineclass/values.yaml
  controllers/provider-gcp/pkg/controller/worker/machines.go
  controllers/provider-gcp/pkg/controller/worker/machines_test.go
Labels: needs/ok-to-test

#555 Vendor gardener/gardener@v0.34.0
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/pkg/api/extensions/accessor.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_shootstate.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_shootstate.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_controlplane.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  vendor/github.com/gardener/gardener/pkg/scheduler/controller/shoot/scheduler_control.go
  vendor/github.com/gardener/gardener/test/integration/framework/garden_operation.go
  vendor/modules.txt
Labels: needs/ok-to-test

#554 Update golangci/golangci-lint to v1.20.1
  .dockerignore
  .golangci.yaml
  hack/check.sh
  hack/install-requirements.sh
Labels: needs/ok-to-test

#560 [ci:component:github.com/gardener/external-dns-management:v0.7.4->v0.7.5]
  controllers/extension-shoot-dns-service/charts/images.yaml
Labels: needs/ok-to-test

#562 Upgrade Calico to v3.11.2
  controllers/networking-calico/charts/images.yaml
  controllers/networking-calico/charts/internal/calico/templates/node/clusterrole-calico-node.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: needs/ok-to-test

#559 Remove support for public IPs in GCP
  controllers/provider-gcp/pkg/controller/worker/machines.go
  controllers/provider-gcp/pkg/controller/worker/machines_test.go
Labels: needs/ok-to-test

#565 Add v1beta1 shoots to AWS webhook chart
  controllers/provider-aws/charts/validator-aws/charts/application/templates/validatingwebhook-validator.yaml
Labels: needs/ok-to-test

#568 Add missing resources for Calico components
  controllers/networking-calico/charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: needs/ok-to-test

#571 Fix usage-as-operator.md docs to match the specs
  controllers/provider-alicloud/docs/usage-as-operator.md
  controllers/provider-aws/docs/usage-as-operator.md
  controllers/provider-azure/docs/usage-as-operator.md
  controllers/provider-gcp/docs/usage-as-operator.md
  controllers/provider-openstack/docs/usage-as-operator.md
  controllers/provider-packet/docs/usage-as-operator.md
Labels: needs/ok-to-test

#573 Add origin:gardener label
  controllers/networking-calico/charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
  controllers/networking-calico/charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: needs/ok-to-test

#570 Increase log level for successful health checks
  pkg/controller/healthcheck/reconciler.go
Labels: needs/ok-to-test

#567 Added custom OpenStack root disk size
  controllers/provider-openstack/charts/internal/machineclass/templates/machineclass.yaml
  controllers/provider-openstack/charts/internal/machineclass/values.yaml
  controllers/provider-openstack/example/30-worker.yaml
  controllers/provider-openstack/pkg/controller/worker/machines.go
Labels: needs/ok-to-test

#574 provider-vsphere: fixing etcd storage provider and parameters
  controllers/provider-vsphere/charts/provider-vsphere/templates/storageclass.yaml
  controllers/provider-vsphere/charts/provider-vsphere/values.yaml
  controllers/provider-vsphere/example/00-componentconfig.yaml
  controllers/provider-vsphere/example/controller-registration.yaml
  controllers/provider-vsphere/hack/api-reference/config.md
  controllers/provider-vsphere/pkg/apis/config/types.go
  controllers/provider-vsphere/pkg/apis/config/v1alpha1/types.go
  controllers/provider-vsphere/pkg/apis/config/v1alpha1/zz_generated.conversion.go
  controllers/provider-vsphere/pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-vsphere/pkg/apis/config/zz_generated.deepcopy.go
  controllers/provider-vsphere/pkg/vsphere/types.go
Labels: needs/ok-to-test

#535 Enable GCP Flow Logs
  controllers/provider-gcp/charts/internal/gcp-infra/templates/main.tf
  controllers/provider-gcp/charts/internal/gcp-infra/values.yaml
  controllers/provider-gcp/docs/usage-as-end-user.md
  controllers/provider-gcp/example/30-infrastructure.yaml
  controllers/provider-gcp/hack/api-reference/api.md
  controllers/provider-gcp/pkg/apis/gcp/types_infrastructure.go
  controllers/provider-gcp/pkg/apis/gcp/v1alpha1/types_infrastructure.go
  controllers/provider-gcp/pkg/apis/gcp/v1alpha1/zz_generated.conversion.go
  controllers/provider-gcp/pkg/apis/gcp/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-gcp/pkg/apis/gcp/validation/infrastructure.go
  controllers/provider-gcp/pkg/apis/gcp/validation/infrastructure_test.go
  controllers/provider-gcp/pkg/apis/gcp/zz_generated.deepcopy.go
  controllers/provider-gcp/pkg/internal/infrastructure/terraform.go
  controllers/provider-gcp/pkg/internal/infrastructure/terraform_test.go
Labels: needs/ok-to-test

#579 [ci:component:github.com/gardener/terraformer:0.17.0->0.18.0]
  controllers/provider-alicloud/charts/images.yaml
  controllers/provider-aws/charts/images.yaml
  controllers/provider-azure/charts/images.yaml
  controllers/provider-gcp/charts/images.yaml
  controllers/provider-openstack/charts/images.yaml
  controllers/provider-packet/charts/images.yaml
  controllers/provider-vsphere/charts/images.yaml
Labels: needs/ok-to-test

#572 Support for slice of similar type of operatingsystemconfigs
  controllers/os-coreos-alicloud/pkg/coreos-alicloud/add.go
  controllers/os-coreos/pkg/coreos/add.go
  pkg/controller/backupbucket/controller.go
  pkg/controller/backupentry/controller.go
  pkg/controller/controlplane/controller.go
  pkg/controller/extension/reconciler.go
  pkg/controller/healthcheck/controller.go
  pkg/controller/infrastructure/controller.go
  pkg/controller/network/controller.go
  pkg/controller/operatingsystemconfig/controller.go
  pkg/controller/operatingsystemconfig/oscommon/add.go
  pkg/controller/worker/controller.go
  pkg/predicate/predicate.go
Labels: needs/ok-to-test

#578 Ensure csi components running on every nodes in Alicloud
  controllers/provider-alicloud/charts/internal/shoot-system-components/charts/csi-alicloud/templates/csi-diskplugin-ds.yaml
Labels: needs/ok-to-test

#581 Add testgrid gardener 1.17 k8s e2e badges
  controllers/provider-alicloud/README.md
  controllers/provider-aws/README.md
  controllers/provider-azure/README.md
  controllers/provider-gcp/README.md
  controllers/provider-openstack/README.md
Labels: needs/ok-to-test

#580 Allow os-coreos controller to handle Flatcar distro
  controllers/os-coreos/README.md
  controllers/os-coreos/charts/os-coreos/doc.go
  controllers/os-coreos/example/controller-registration.yaml
  controllers/os-coreos/pkg/coreos/add.go
Labels: needs/ok-to-test

#585 provider-vsphere: added healthcheck controller
  controllers/provider-vsphere/cmd/gardener-extension-provider-vsphere/app/app.go
  controllers/provider-vsphere/example/00-componentconfig.yaml
  controllers/provider-vsphere/hack/api-reference/config.md
  controllers/provider-vsphere/hack/generate-code
  controllers/provider-vsphere/pkg/apis/config/types.go
  controllers/provider-vsphere/pkg/apis/config/v1alpha1/types.go
  controllers/provider-vsphere/pkg/apis/config/v1alpha1/zz_generated.conversion.go
  controllers/provider-vsphere/pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  controllers/provider-vsphere/pkg/apis/config/zz_generated.deepcopy.go
  controllers/provider-vsphere/pkg/cmd/config.go
  controllers/provider-vsphere/pkg/cmd/options.go
  controllers/provider-vsphere/pkg/controller/controlplane/valuesprovider.go
  controllers/provider-vsphere/pkg/controller/healthcheck/add.go
  controllers/provider-vsphere/pkg/vsphere/types.go
Labels: needs/ok-to-test

#588 Make hack/generate-controller-registration.sh work with helm 3
  hack/generate-controller-registration.sh
Labels: needs/ok-to-test

#589 Allow to extend workerpool hash with addional data
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: needs/ok-to-test
